import assert from "node:assert/strict";
import test from "node:test";
import { normalizeFamilyRelationship, resolveFamilyRelationship, sortFamilyRelationships, type FamilyArtist, type FamilyRelationshipItem, type FamilyRelationshipRow } from "../../src/lib/artistFamilyRelationships.ts";

const ramon: FamilyArtist = {id:"b",name:"Ramón Orlando",slug:"ramon-orlando",gender:"male",date_of_death:null,death_year:null};
const cuco: FamilyArtist = {id:"a",name:"Cuco Valoy",slug:"cuco-valoy",gender:"male",date_of_death:null,death_year:null};
test("Father input stores one parent row and resolves both perspectives",()=>{const normalized=normalizeFamilyRelationship(ramon.id,cuco.id,"father");assert.deepEqual(normalized,{artist_id:cuco.id,related_artist_id:ramon.id,relationship_type:"parent",relationship_status:null});const row={id:"r",...normalized,artist:cuco,related_artist:ramon} as FamilyRelationshipRow;assert.equal(resolveFamilyRelationship(row,ramon.id)?.labelKey,"father");assert.equal(resolveFamilyRelationship(row,cuco.id)?.labelKey,"son");});
test("symmetric relationships canonicalize in either direction",()=>{assert.deepEqual(normalizeFamilyRelationship("b","a","brother"),normalizeFamilyRelationship("a","b","sister"));});
test("former spouse resolves gendered inverse labels",()=>{const normalized=normalizeFamilyRelationship("b","a","ex_husband");const row={id:"s",...normalized,artist:cuco,related_artist:{...ramon,gender:"female"}} as FamilyRelationshipRow;assert.equal(resolveFamilyRelationship(row,"a")?.labelKey,"ex_wife");assert.equal(resolveFamilyRelationship(row,"b")?.labelKey,"ex_husband");});
test("self relationships are rejected",()=>assert.throws(()=>normalizeFamilyRelationship("a","a","sibling"),/cannot be related/));
test("death-ended spouse uses survivor and late-spouse semantics only with death data",()=>{const survivor={...ramon,gender:"female"};const late={...cuco,date_of_death:"2020-01-01"};const normalized=normalizeFamilyRelationship(survivor.id,late.id,"widow_of");const row={id:"d",...normalized,artist:late,related_artist:survivor} as FamilyRelationshipRow;assert.equal(resolveFamilyRelationship(row,survivor.id)?.labelKey,"widow_of");assert.equal(resolveFamilyRelationship(row,late.id)?.labelKey,"late_wife");});
test("great-uncle input stores one canonical row and resolves great-nephew inversely",()=>{const jura={...ramon,name:"Jura Valoy",slug:"jura-valoy"};const martin={...cuco,name:"Martín Valoy",slug:"martin-valoy"};const normalized=normalizeFamilyRelationship(jura.id,martin.id,"great_uncle");assert.deepEqual(normalized,{artist_id:martin.id,related_artist_id:jura.id,relationship_type:"great_uncle_aunt",relationship_status:null});const row={id:"gu",...normalized,artist:martin,related_artist:jura} as FamilyRelationshipRow;assert.equal(resolveFamilyRelationship(row,jura.id)?.labelKey,"great_uncle");assert.equal(resolveFamilyRelationship(row,martin.id)?.labelKey,"great_nephew");});
test("great-aunt input resolves great-niece and inverse entry canonicalizes identically",()=>{const younger={...ramon,gender:"female"};const aunt={...cuco,gender:"female"};const fromYounger=normalizeFamilyRelationship(younger.id,aunt.id,"great_aunt");const fromAunt=normalizeFamilyRelationship(aunt.id,younger.id,"great_niece");assert.deepEqual(fromYounger,fromAunt);const row={id:"ga",...fromYounger,artist:aunt,related_artist:younger} as FamilyRelationshipRow;assert.equal(resolveFamilyRelationship(row,younger.id)?.labelKey,"great_aunt");assert.equal(resolveFamilyRelationship(row,aunt.id)?.labelKey,"great_niece");});
test("Facts Card family order places parents before siblings and siblings before children",()=>{const item=(id:string,name:string,labelKey:FamilyRelationshipItem["labelKey"]):FamilyRelationshipItem=>({id,relatedArtist:{...ramon,id,name},relationshipType:"parent",relationshipStatus:null,labelKey});const sorted=sortFamilyRelationships([item("son","Son","son"),item("brother","Brother","brother"),item("father","Father","father")]);assert.deepEqual(sorted.map((relationship)=>relationship.labelKey),["father","brother","son"]);});
