import assert from "node:assert/strict";
import test from "node:test";
import { normalizeFamilyRelationship, resolveFamilyRelationship, sortFamilyRelationships, type FamilyArtist, type FamilyRelationshipItem, type FamilyRelationshipRow } from "../../src/lib/artistFamilyRelationships.ts";

const ramon: FamilyArtist = {id:"b",name:"Ramón Orlando",slug:"ramon-orlando",gender:"male",date_of_death:null,death_year:null};
const cuco: FamilyArtist = {id:"a",name:"Cuco Valoy",slug:"cuco-valoy",gender:"male",date_of_death:null,death_year:null};
test("Father input stores one parent row and resolves both perspectives",()=>{const normalized=normalizeFamilyRelationship(ramon.id,cuco.id,"father");assert.deepEqual(normalized,{artist_id:cuco.id,related_artist_id:ramon.id,relationship_type:"parent",relationship_status:null});const row={id:"r",...normalized,artist:cuco,related_artist:ramon} as FamilyRelationshipRow;assert.equal(resolveFamilyRelationship(row,ramon.id)?.labelKey,"father");assert.equal(resolveFamilyRelationship(row,cuco.id)?.labelKey,"son");});
test("symmetric relationships canonicalize in either direction",()=>{assert.deepEqual(normalizeFamilyRelationship("b","a","brother"),normalizeFamilyRelationship("a","b","sister"));});
test("former spouse resolves gendered inverse labels",()=>{const normalized=normalizeFamilyRelationship("b","a","ex_husband");const row={id:"s",...normalized,artist:cuco,related_artist:{...ramon,gender:"female"}} as FamilyRelationshipRow;assert.equal(resolveFamilyRelationship(row,"a")?.labelKey,"ex_wife");assert.equal(resolveFamilyRelationship(row,"b")?.labelKey,"ex_husband");});
test("self relationships are rejected",()=>assert.throws(()=>normalizeFamilyRelationship("a","a","sibling"),/cannot be related/));
test("death-ended spouse uses survivor and late-spouse semantics only with death data",()=>{const survivor={...ramon,gender:"female"};const late={...cuco,date_of_death:"2020-01-01"};const normalized=normalizeFamilyRelationship(survivor.id,late.id,"widow_of");const row={id:"d",...normalized,artist:late,related_artist:survivor} as FamilyRelationshipRow;assert.equal(resolveFamilyRelationship(row,survivor.id)?.labelKey,"widow_of");assert.equal(resolveFamilyRelationship(row,late.id)?.labelKey,"late_wife");});
test("great-uncle input stores one canonical row and resolves great-nephew inversely",()=>{const jura={...ramon,name:"Jura Valoy",slug:"jura-valoy"};const martin={...cuco,name:"Martín Valoy",slug:"martin-valoy"};const normalized=normalizeFamilyRelationship(jura.id,martin.id,"great_uncle");assert.deepEqual(normalized,{artist_id:martin.id,related_artist_id:jura.id,relationship_type:"great_uncle_aunt",relationship_status:null});const row={id:"gu",...normalized,artist:martin,related_artist:jura} as FamilyRelationshipRow;assert.equal(resolveFamilyRelationship(row,jura.id)?.labelKey,"great_uncle");assert.equal(resolveFamilyRelationship(row,martin.id)?.labelKey,"great_nephew");});
test("great-aunt input resolves great-niece and inverse entry canonicalizes identically",()=>{const younger={...ramon,gender:"female"};const aunt={...cuco,gender:"female"};const fromYounger=normalizeFamilyRelationship(younger.id,aunt.id,"great_aunt");const fromAunt=normalizeFamilyRelationship(aunt.id,younger.id,"great_niece");assert.deepEqual(fromYounger,fromAunt);const row={id:"ga",...fromYounger,artist:aunt,related_artist:younger} as FamilyRelationshipRow;assert.equal(resolveFamilyRelationship(row,younger.id)?.labelKey,"great_aunt");assert.equal(resolveFamilyRelationship(row,aunt.id)?.labelKey,"great_niece");});
test("Facts Card family order places parents before siblings and siblings before children",()=>{const item=(id:string,name:string,labelKey:FamilyRelationshipItem["labelKey"]):FamilyRelationshipItem=>({id,relatedArtist:{...ramon,id,name},relationshipType:"parent",relationshipStatus:null,labelKey});const sorted=sortFamilyRelationships([item("son","Son","son"),item("brother","Brother","brother"),item("father","Father","father")]);assert.deepEqual(sorted.map((relationship)=>relationship.labelKey),["father","brother","son"]);});
test("cousin resolves a gendered label per side so Spanish can say primo or prima",()=>{const rafely={id:"c1",name:"Rafely Rosario",slug:"rafely-rosario",gender:"male",date_of_death:null,death_year:null} as FamilyArtist;const prima={id:"c2",name:"Prima Rosario",slug:"prima-rosario",gender:"female",date_of_death:null,death_year:null} as FamilyArtist;const normalized=normalizeFamilyRelationship(rafely.id,prima.id,"cousin");const row={id:"cz",...normalized,artist:rafely,related_artist:prima} as FamilyRelationshipRow;assert.equal(resolveFamilyRelationship(row,rafely.id)?.labelKey,"female_cousin");assert.equal(resolveFamilyRelationship(row,prima.id)?.labelKey,"male_cousin");});
test("cousin with unknown gender falls back to the neutral label",()=>{const a={id:"c1",name:"A",slug:"a",gender:null,date_of_death:null,death_year:null} as FamilyArtist;const b={id:"c2",name:"B",slug:"b",gender:null,date_of_death:null,death_year:null} as FamilyArtist;const normalized=normalizeFamilyRelationship(a.id,b.id,"cousin");const row={id:"cn",...normalized,artist:a,related_artist:b} as FamilyRelationshipRow;assert.equal(resolveFamilyRelationship(row,a.id)?.labelKey,"cousin");});
test("uncle and nephew fall back to family labels, not parent and child, when gender is unknown",()=>{const tio={id:"u1",name:"Tío",slug:"tio",gender:null,date_of_death:null,death_year:null} as FamilyArtist;const sobrino={id:"u2",name:"Sobrino",slug:"sobrino",gender:null,date_of_death:null,death_year:null} as FamilyArtist;const normalized=normalizeFamilyRelationship(sobrino.id,tio.id,"uncle");const row={id:"ua",...normalized,artist:tio,related_artist:sobrino} as FamilyRelationshipRow;assert.equal(resolveFamilyRelationship(row,sobrino.id)?.labelKey,"uncle_aunt");assert.equal(resolveFamilyRelationship(row,tio.id)?.labelKey,"nibling");});
test("every presentation key produced by the resolver has a label in both locales",async()=>{const en=JSON.parse(await import("node:fs").then(m=>m.promises.readFile("messages/en.json","utf8")));const es=JSON.parse(await import("node:fs").then(m=>m.promises.readFile("messages/es.json","utf8")));for(const key of ["male_cousin","female_cousin","cousin","uncle_aunt","nibling","great_uncle_aunt","great_nibling","late_husband","late_wife"]){assert.ok(en.family.labels[key],`missing en label: ${key}`);assert.ok(es.family.labels[key],`missing es label: ${key}`);}assert.equal(es.family.labels.male_cousin,"Primo");assert.equal(es.family.labels.female_cousin,"Prima");});
