"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { Pencil, Plus, X } from "lucide-react";
import { AdminField, AdminSearchPicker, adminButtonClass, adminInputClass, type PickerOption } from "@/components/admin/CatalogAdminControls";
import { createClientUuid } from "@/lib/clientUuid";

type Identity = { id: string; name: string };
type Role = { id: string; code: string; display_name_en: string; role_family: string; normal_scope: string; credit_role_scopes?: { scope: string }[] };
type Instrument = { id: string; code: string; display_name_en: string };
type Source = { id: string; title: string; source_type: string; visibility: string };
type Credit = { id: string; role: string; role_id: string | null; credited_as: string | null; display_order: number | null; metadata: { credit_detail?: string } | null; artist: { id: string; name: string; slug: string | null } | null; external_contributor: { id: string; preferred_name: string } | null; role_definition: Role | null; recording_credit_instruments: { instrument_id: string; sequence: number; instrument: Instrument | null }[] };

const FAMILY_LABELS: Record<string, string> = { performance: "Performers & Musicians", production: "Production", arrangement: "Arrangement & Direction", direction: "Arrangement & Direction", engineering: "Engineering", composition: "Work-scope credits requiring review", legacy: "Legacy credits requiring review" };
const FAMILY_ORDER = ["performance", "production", "arrangement", "direction", "engineering", "composition", "legacy"];
function one<T>(value: T | T[] | null): T | null { return Array.isArray(value) ? value[0] ?? null : value; }

export default function RecordingCreditsManager({ recordingId, workId, openEditorRequest = 0 }: { recordingId: string; recordingSlug: string | null; workId?: string | null; openEditorRequest?: number }) {
  const [credits, setCredits] = useState<Credit[]>([]); const [roles, setRoles] = useState<Role[]>([]); const [instruments, setInstruments] = useState<Instrument[]>([]); const [sources, setSources] = useState<Source[]>([]); const [message, setMessage] = useState(""); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Credit | null>(null); const [artist, setArtist] = useState<Identity | null>(null); const [external, setExternal] = useState<Identity | null>(null); const [roleId, setRoleId] = useState(""); const [creditedAs, setCreditedAs] = useState(""); const [creditDetail, setCreditDetail] = useState(""); const [instrumentIds, setInstrumentIds] = useState<string[]>([]); const [sourceIds, setSourceIds] = useState<string[]>([]); const [showQuickCreate, setShowQuickCreate] = useState(false); const [externalName, setExternalName] = useState(""); const [externalCountry, setExternalCountry] = useState(""); const [loading, setLoading] = useState(false);
  const load = useCallback(async () => { setLoading(true); const response = await fetch(`/api/admin/recording-credits?recordingId=${encodeURIComponent(recordingId)}`); const result = await response.json(); setLoading(false); if (!response.ok) { setMessage(result.error ?? "Credits could not be loaded."); return; } setCredits((result.credits ?? []).map((credit: Credit) => ({ ...credit, artist: one(credit.artist), external_contributor: one(credit.external_contributor), role_definition: one(credit.role_definition), recording_credit_instruments: (credit.recording_credit_instruments ?? []).map((item) => ({ ...item, instrument: one(item.instrument) })) }))); setRoles(result.roles ?? []); setInstruments(result.instruments ?? []); setSources(result.sources ?? []); }, [recordingId]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  function begin(credit?: Credit) { setEditing(credit ?? null); setArtist(credit?.artist ? { id: credit.artist.id, name: credit.artist.name } : null); setExternal(credit?.external_contributor ? { id: credit.external_contributor.id, name: credit.external_contributor.preferred_name } : null); setRoleId(credit?.role_id ?? ""); setCreditedAs(credit?.credited_as ?? ""); setCreditDetail(credit?.metadata?.credit_detail ?? ""); setInstrumentIds((credit?.recording_credit_instruments ?? []).map((item) => item.instrument_id)); setSourceIds([]); setOpen(true); setMessage(""); }
  useEffect(() => { if (openEditorRequest <= 0) return; const timer = window.setTimeout(() => begin(), 0); return () => window.clearTimeout(timer); }, [openEditorRequest]);
  async function save() { if ((!artist && !external) || !roleId) { setMessage("Choose one contributor identity and a controlled Recording role."); return; } setLoading(true); const response = await fetch("/api/admin/recording-credits", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ recordingId, creditId: editing?.id ?? null, idempotencyKey: createClientUuid(), artistId: artist?.id ?? null, externalContributorId: external?.id ?? null, roleId, creditedAs, creditDetail, instrumentIds, sourceIds, displayOrder: editing?.display_order ?? credits.length }) }); const result = await response.json(); setLoading(false); if (!response.ok) { setMessage(result.error ?? "Credit could not be saved."); return; } setOpen(false); setMessage(editing ? "Recording Credit updated through governed workflow." : "Recording Credit created through governed workflow."); await load(); }
  async function quickCreate() { if (!externalName.trim()) return; const response = await fetch("/api/admin/external-contributors", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ preferredName: externalName, country: externalCountry || null, sourceIds, idempotencyKey: createClientUuid() }) }); const result = await response.json(); if (!response.ok) { setMessage(result.error ?? "External Contributor could not be created."); return; } const id = result.result?.external_contributor_id; if (id) { setExternal({ id, name: externalName.trim() }); setArtist(null); setShowQuickCreate(false); setExternalName(""); setExternalCountry(""); } }
  const selectedRole = roles.find((role) => role.id === roleId); const grouped = new Map<string, Credit[]>(); for (const credit of credits) { const family = credit.role_definition?.role_family ?? (["composer", "songwriter", "lyricist"].includes(credit.role.toLowerCase()) ? "composition" : "legacy"); grouped.set(family, [...(grouped.get(family) ?? []), credit]); }

  return <section id="recording-credits" className="scroll-mt-6 rounded-xl border border-gray-100 bg-white p-5 shadow-sm">
    <div className="flex items-center justify-between gap-3"><div><h2 className="text-xs uppercase tracking-[0.2em] text-(--color-wikicrimson)">Recording Credits</h2><p className="mt-2 text-sm text-gray-500">People who contributed to this particular recorded performance.</p></div><button type="button" onClick={() => begin()} className={adminButtonClass}><Plus className="mr-2 inline h-4 w-4" />Add Recording Credit</button></div>
    <div className="mt-4 rounded-lg border border-blue-100 bg-blue-50/50 p-3 text-sm text-gray-700"><b>Composition authorship belongs to the Work.</b><p className="mt-1 text-xs">Composer, songwriter, and lyricist are documented once on the Composition, not repeated on each Recording.</p>{workId ? <Link className="mt-2 inline-flex font-medium text-(--color-flagblue)" href={`/admin/authoritative-works?workId=${encodeURIComponent(workId)}#composition-credits`}>Open Work Credits</Link> : <p className="mt-2 text-xs font-medium text-amber-700">Create or link a Composition first to document those credits.</p>}</div>
    {message && <p role="status" className="mt-3 rounded border bg-gray-50 p-2 text-sm">{message}</p>}
    {loading && !credits.length ? <p className="mt-4 text-sm text-gray-500">Loading…</p> : credits.length ? <div className="mt-5 space-y-5">{FAMILY_ORDER.filter((family) => grouped.has(family)).map((family) => <div key={family}><h3 className="mb-2 text-xs font-bold uppercase tracking-wide text-gray-500">{FAMILY_LABELS[family]}</h3><div className="space-y-2">{grouped.get(family)!.map((credit) => { const identityName = credit.artist?.name ?? credit.external_contributor?.preferred_name ?? "Missing contributor"; return <div key={credit.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border bg-gray-50 p-3"><div>{credit.artist ? <Link href={`/admin/artists?artistId=${credit.artist.id}`} className="font-medium text-(--color-flagblue) hover:underline">{identityName}</Link> : credit.external_contributor ? <Link href={`/admin/external-contributors?id=${credit.external_contributor.id}`} className="font-medium text-(--color-flagblue) hover:underline">{identityName}</Link> : <b>{identityName}</b>}<p className="text-xs text-gray-500">{credit.role_definition?.display_name_en ?? credit.role}{credit.credited_as ? ` · credited as ${credit.credited_as}` : ""}{credit.recording_credit_instruments?.length ? ` · ${credit.recording_credit_instruments.map((item) => item.instrument?.display_name_en).filter(Boolean).join(", ")}` : ""}</p>{family === "composition" && <p className="mt-1 text-xs font-medium text-amber-700">This is a legacy Work-scope role. Review it later; it was not moved automatically.</p>}</div><button type="button" onClick={() => begin(credit)} className="rounded p-2" aria-label={`Edit ${identityName}`}><Pencil className="h-4 w-4" /></button></div>; })}</div></div>)}</div> : <p className="mt-4 rounded-lg border border-dashed bg-gray-50 p-4 text-sm text-gray-500">No Recording Credits documented.</p>}
    {open && <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-black/40 p-4"><div role="dialog" aria-modal="true" aria-labelledby="credit-dialog-title" className="my-8 w-full max-w-2xl rounded-xl bg-white p-6 shadow-xl"><div className="flex justify-between"><h3 id="credit-dialog-title" className="text-lg font-semibold text-(--color-flagblue)">{editing ? "Edit Recording Credit" : "Add Recording Credit"}</h3><button type="button" onClick={() => setOpen(false)} aria-label="Close"><X /></button></div><div className="mt-5 space-y-4">
      <div className="grid gap-4 md:grid-cols-2"><div className="rounded-lg border p-3"><h4 className="mb-2 text-xs font-bold uppercase">Mangulina Artists</h4><AdminSearchPicker label="Artist" value={artist?.id ?? ""} displayValue={artist?.name ?? ""} placeholder="Search Artist…" endpoint="/api/admin/artists" resultKey="artists" onSelect={(option: PickerOption) => { setArtist({ id: option.id, name: option.name ?? "Artist" }); setExternal(null); }} onClear={() => setArtist(null)} /></div><div className="rounded-lg border p-3"><h4 className="mb-2 text-xs font-bold uppercase">External Contributors</h4><AdminSearchPicker label="External Contributor" value={external?.id ?? ""} displayValue={external?.name ?? ""} placeholder="Search external identity…" endpoint="/api/admin/external-contributors" resultKey="external_contributors" onSelect={(option: PickerOption) => { setExternal({ id: option.id, name: option.title ?? "External Contributor" }); setArtist(null); }} onClear={() => setExternal(null)} /><button type="button" className="mt-2 text-sm text-(--color-flagblue)" onClick={() => setShowQuickCreate(true)}>Add External Contributor</button></div></div>
      <AdminField label="Controlled Recording role"><select value={roleId} onChange={(event) => { setRoleId(event.target.value); if (roles.find((role) => role.id === event.target.value)?.code !== "instrumentalist") setInstrumentIds([]); }} className={adminInputClass}><option value="">Choose role…</option>{roles.filter((role) => role.code !== "pianist").map((role) => <option key={role.id} value={role.id}>{role.display_name_en} · {FAMILY_LABELS[role.role_family] ?? role.role_family}</option>)}</select><p className="mt-1 text-xs text-gray-500">Composer, songwriter, and lyricist are managed by the Composition (Work).</p>{selectedRole?.code === "arranger" && <p className="mt-2 rounded border border-amber-200 bg-amber-50 p-2 text-xs text-amber-900">Arranger can describe the composition or this specific recorded version. Choose Recording only when the evidence describes this performance; otherwise document it on the Work.</p>}</AdminField>
      {selectedRole?.code === "instrumentalist" && <fieldset className="rounded-lg border p-3"><legend className="px-1 text-xs font-bold uppercase">Instruments</legend>{instruments.map((instrument) => <label key={instrument.id} className="mr-4 inline-flex items-center gap-2 text-sm"><input type="checkbox" checked={instrumentIds.includes(instrument.id)} onChange={(event) => setInstrumentIds((current) => event.target.checked ? [...current, instrument.id] : current.filter((id) => id !== instrument.id))} />{instrument.display_name_en}</label>)}</fieldset>}
      <AdminField label="Credited as"><input maxLength={200} value={creditedAs} onChange={(event) => setCreditedAs(event.target.value)} className={adminInputClass} /></AdminField><AdminField label="Role-specific detail"><input maxLength={300} value={creditDetail} onChange={(event) => setCreditDetail(event.target.value)} className={adminInputClass} placeholder="Specific responsibility documented by the source" /></AdminField>
      <fieldset className="rounded-lg border p-3"><legend className="px-1 text-xs font-bold uppercase">Supporting evidence</legend><div className="max-h-36 space-y-2 overflow-y-auto">{sources.map((source) => <label key={source.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={sourceIds.includes(source.id)} onChange={(event) => setSourceIds((current) => event.target.checked ? [...current, source.id] : current.filter((id) => id !== source.id))} /><span>{source.title} <small className="text-gray-400">{source.source_type} · {source.visibility}</small></span></label>)}</div></fieldset>
      <div className="flex gap-2"><button type="button" disabled={loading} onClick={() => void save()} className={adminButtonClass}>Save governed credit</button><button type="button" onClick={() => setOpen(false)} className="rounded-lg border px-5 py-3 text-xs uppercase">Cancel</button></div>
    </div></div></div>}
    {showQuickCreate && <div className="fixed inset-0 z-60 flex items-center justify-center bg-black/50 p-4"><div role="dialog" aria-modal="true" aria-labelledby="quick-external-title" className="w-full max-w-md space-y-3 rounded-xl bg-white p-5"><h3 id="quick-external-title" className="text-lg font-bold">Add External Contributor</h3><input autoFocus required className={adminInputClass} value={externalName} onChange={(event) => setExternalName(event.target.value)} placeholder="Name *" /><input className={adminInputClass} value={externalCountry} onChange={(event) => setExternalCountry(event.target.value)} placeholder="Country (optional)" /><div className="flex justify-end gap-2"><button type="button" className="rounded-lg border px-4 py-2" onClick={() => setShowQuickCreate(false)}>Cancel</button><button type="button" disabled={!externalName.trim()} className={adminButtonClass} onClick={() => void quickCreate()}>Create and select</button></div></div></div>}
  </section>;
}
