"use client";

import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { useTranslations } from "next-intl";
import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { AdminSearchPicker, type PickerOption } from "@/components/admin/CatalogAdminControls";
import { createClientUuid } from "@/lib/clientUuid";

type Source = { id: string; title: string; source_type: string; visibility: string };
type Role = { id: string; code: string; display_name_en: string; normal_scope: string; credit_role_scopes: { scope: string }[] };
type Evidence = { sourceId: string; relationship: "supports" | "disputes" | "contextualizes" };
type Approval = { id: string; decision_type: string; reason: string; requested_at: string; previous_canonical_state: Record<string, unknown>; resulting_canonical_state: Record<string, unknown> };
type Work = { id: string; preferred_title: string; composition_year: number | null; publication_year: number | null; status: string; language: string | null };
type Recording = { id: string; title: string; recording_year: number | null; duration: number | null; disambiguation: string | null; artist: { id: string; name: string } | { id: string; name: string }[] | null };
type WorkCredit = { id: string; role: string; credited_as: string | null; verification_status: string; artist: { id: string; name: string } | { id: string; name: string }[] | null; external_contributor: { id: string; preferred_name: string; country: string | null } | { id: string; preferred_name: string; country: string | null }[] | null };

const input = "w-full rounded-lg border border-gray-200 px-3 py-2 text-sm";
const button = "rounded-lg bg-(--color-flagblue) px-4 py-2 text-sm text-white disabled:opacity-50";
const card = "rounded-xl border bg-white p-5 shadow-sm";
function one<T>(value: T | T[] | null): T | null { return Array.isArray(value) ? value[0] ?? null : value; }

export default function WorkWorkspacePage() {
  const t = useTranslations("admin.workWorkspace");
  const adminT = useTranslations("admin");
  const params = useSearchParams();
  const linkPrompt = params.get("linkPrompt") === "1";
  const [workId, setWorkId] = useState(params.get("workId") ?? ""); const [workName, setWorkName] = useState(""); const [work, setWork] = useState<Work | null>(null); const [linkedRecordings, setLinkedRecordings] = useState<Recording[]>([]); const [existingCredits, setExistingCredits] = useState<WorkCredit[]>([]);
  const [newTitle, setNewTitle] = useState(""); const [compositionYear, setCompositionYear] = useState(""); const [publicationYear, setPublicationYear] = useState("");
  const [recordingId, setRecordingId] = useState(params.get("recordingId") ?? ""); const [recordingName, setRecordingName] = useState("");
  const [artistId, setArtistId] = useState(""); const [artistName, setArtistName] = useState(""); const [externalId, setExternalId] = useState(""); const [externalName, setExternalName] = useState("");
  const [roles, setRoles] = useState<Role[]>([]); const [roleId, setRoleId] = useState(""); const [creditedAs, setCreditedAs] = useState(""); const [creditAssertionId, setCreditAssertionId] = useState("");
  const [sources, setSources] = useState<Source[]>([]); const [evidence, setEvidence] = useState<Evidence[]>([]); const [sourceTitle, setSourceTitle] = useState("");
  const [approvals, setApprovals] = useState<Approval[]>([]); const [history, setHistory] = useState<Record<string, unknown>[]>([]); const [message, setMessage] = useState("");
  const [showExternalCreate, setShowExternalCreate] = useState(false); const [newExternalName, setNewExternalName] = useState(""); const [newExternalCountry, setNewExternalCountry] = useState("");

  async function bootstrap() { const data = await fetch("/api/admin/editorial-workflows").then((r) => r.json()); setRoles(data.roles ?? []); setSources(data.sources ?? []); const pending = await fetch("/api/admin/editorial-workflows?kind=approvals").then((r) => r.json()); setApprovals(pending.approvals ?? []); }
  async function loadWork(id: string) { const data = await fetch(`/api/admin/editorial-workflows?kind=work&id=${encodeURIComponent(id)}`).then((r) => r.json()); if (!data.ok) { setMessage(data.error ?? "Work could not be loaded."); return; } setWork(data.work); setWorkName(data.work?.preferred_title ?? "Work"); setLinkedRecordings(data.linked_recordings ?? []); setExistingCredits((data.credits ?? []).map((credit: WorkCredit) => ({ ...credit, artist: one(credit.artist), external_contributor: one(credit.external_contributor) }))); }
  useEffect(() => { const timer = window.setTimeout(() => { void bootstrap(); if (workId) void loadWork(workId); if (recordingId && !recordingName) void fetch(`/api/admin/recordings?id=${encodeURIComponent(recordingId)}`).then((response) => response.json()).then((data) => setRecordingName(data.recordings?.[0]?.title ?? "Originating Recording")); }, 0); return () => window.clearTimeout(timer); }, [workId, recordingId, recordingName]);
  async function act(action: string, extra: Record<string, unknown>) { const response = await fetch("/api/admin/editorial-workflows", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, idempotencyKey: createClientUuid(), ...extra }) }); const data = await response.json(); setMessage(response.ok ? "Saved." : data.error); if (response.ok) { await bootstrap(); if (workId) await loadWork(workId); } return response.ok ? data.result : null; }
  const sourceIds = [...new Set(evidence.filter((item) => item.relationship === "supports").map((item) => item.sourceId))]; const workRoles = roles.filter((role) => role.credit_role_scopes.some((scope) => scope.scope === "work")); const hasIdentity = Boolean(artistId || externalId);
  async function createWork() { const result = await act("work.create", { title: newTitle, compositionYear: compositionYear ? Number(compositionYear) : null, publicationYear: publicationYear ? Number(publicationYear) : null, sourceIds }); if (result?.work_id) { setWorkId(result.work_id); setWorkName(newTitle.trim()); await loadWork(result.work_id); } }
  async function addCredit() { const action = externalId ? "credit.create.external" : "credit.create"; const result = await act(action, { workId, artistId, externalContributorId: externalId, roleId, creditedAs, sourceIds }); if (result?.assertion_id) setCreditAssertionId(result.assertion_id); }
  async function linkRecording() { const assertion = await act("work.assert", { recordingId, workId, sourceIds }); if (assertion?.assertion_id) { await act("work.select", { assertionId: assertion.assertion_id, reason: "Editor linked this Recording to the selected Work after reviewing the available evidence." }); await loadWork(workId); setRecordingId(""); setRecordingName(""); } }
  async function createExternalContributor() { if (!newExternalName.trim()) return; const response = await fetch("/api/admin/external-contributors", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ preferredName: newExternalName, country: newExternalCountry || null, sourceIds, idempotencyKey: createClientUuid() }) }); const data = await response.json(); if (!response.ok) { setMessage(data.error ?? "External Contributor could not be created."); return; } const id = data.result?.external_contributor_id; if (id) { setExternalId(id); setExternalName(newExternalName.trim()); setArtistId(""); setArtistName(""); setShowExternalCreate(false); } }
  async function loadHistory() { if (!recordingId) { setMessage("Select a Recording first to view its relationship history."); return; } const data = await fetch(`/api/admin/editorial-workflows?kind=history&recordingId=${recordingId}`).then((r) => r.json()); setHistory(data.history ?? []); }

  return <main className="min-h-screen bg-gray-50 px-5 pb-10 pt-8 font-sans text-gray-900 sm:px-6 sm:pb-12 sm:pt-10"><div className="mx-auto max-w-5xl space-y-6"><header className="rounded-xl border border-black/5 bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-medium uppercase tracking-[0.22em] text-[#CE1126]">{adminT("ui.branding")}</p><h1 className="mt-3 text-3xl font-black uppercase tracking-tight text-[#002D62] sm:text-4xl">{t("title")}</h1><p className="mt-4 max-w-3xl text-sm leading-relaxed text-gray-600 sm:text-base">{t("description")}</p></div><Link href="/admin" className="inline-flex w-fit shrink-0 items-center gap-2 rounded-lg border border-gray-200 bg-white px-4 py-2 text-xs font-normal uppercase tracking-[0.18em] text-[#002D62] shadow-sm transition hover:border-[#CE1126] hover:text-[#CE1126]"><ArrowLeft className="h-4 w-4" aria-hidden="true" />{t("backToPortal")}</Link></div></header>{message && <p role="status" className="rounded-lg border bg-white px-4 py-3 text-sm">{message}</p>}
    <section className={card}><div className="mb-4 flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-(--color-flagblue) text-sm text-white">1</span><div><h2 className="font-bold">Find the song</h2><p className="text-sm text-gray-500">Search before creating a new Work.</p></div></div><AdminSearchPicker label="Existing Work" value={workId} displayValue={workName} placeholder="Search Works…" endpoint="/api/admin/editorial-workflows" extraParams={{ kind: "works" }} resultKey="works" onSelect={(option: PickerOption) => { setWorkId(option.id); setWorkName(option.title ?? "Work"); void loadWork(option.id); }} onClear={() => { setWorkId(""); setWorkName(""); setWork(null); setLinkedRecordings([]); setExistingCredits([]); }} />{!work && <div className="mt-5 rounded-xl border border-dashed bg-gray-50 p-5"><h3 className="font-semibold">No Work selected</h3><p className="mt-1 text-sm text-gray-500">If the song is not already in Mangulina, create it here.</p><div className="mt-4 grid gap-3 md:grid-cols-3"><input className={`${input} md:col-span-3`} value={newTitle} onChange={(event) => setNewTitle(event.target.value)} placeholder="Work title *" /><input className={input} type="number" value={compositionYear} onChange={(event) => setCompositionYear(event.target.value)} placeholder="Composition year" /><input className={input} type="number" value={publicationYear} onChange={(event) => setPublicationYear(event.target.value)} placeholder="Publication year" /><button className={button} disabled={!newTitle.trim()} onClick={() => void createWork()}>Create Work</button></div></div>}</section>
    {work && <>{linkPrompt && recordingId && <section className="rounded-xl border-2 border-(--color-flagblue)/25 bg-(--color-flagblue)/5 p-5"><p className="text-xs font-bold uppercase tracking-[0.18em] text-(--color-wikicrimson)">Continue from Recording</p><h2 className="mt-2 text-xl font-black text-(--color-flagblue)">{recordingName || "Originating Recording"}</h2><p className="mt-1 text-sm text-gray-600">The Work now exists. Confirm whether this Recording should be linked to it, or leave the relationship unresolved for further research.</p><div className="mt-4 flex flex-wrap gap-3"><button className={button} onClick={() => void linkRecording()}>Link this Recording</button><button className="rounded-lg border bg-white px-4 py-2 text-sm" onClick={() => { setRecordingId(""); setRecordingName(""); setMessage("The Recording remains unresolved. The new Work was preserved."); }}>Leave Unresolved</button></div></section>}<section className={card}><div className="mb-4 flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-(--color-flagblue) text-sm text-white">2</span><h2 className="font-bold">Song identity</h2></div><dl className="grid gap-4 text-sm sm:grid-cols-4"><div><dt className="text-xs uppercase text-gray-400">Title</dt><dd className="mt-1 font-semibold">{work.preferred_title}</dd></div><div><dt className="text-xs uppercase text-gray-400">Composition year</dt><dd className="mt-1">{work.composition_year ?? "Unknown"}</dd></div><div><dt className="text-xs uppercase text-gray-400">Publication year</dt><dd className="mt-1">{work.publication_year ?? "Unknown"}</dd></div><div><dt className="text-xs uppercase text-gray-400">Status</dt><dd className="mt-1 capitalize">{work.status}</dd></div></dl></section>
      <section className={card}><div className="mb-4 flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-(--color-flagblue) text-sm text-white">3</span><div><h2 className="font-bold">Composition credits</h2><p className="text-sm text-gray-500">Document who created the composition—not who performed a particular recording.</p></div></div>{existingCredits.length > 0 && <div className="mb-5 space-y-2">{existingCredits.map((credit) => { const artist = one(credit.artist); const external = one(credit.external_contributor); return <div key={credit.id} className="rounded-lg border bg-gray-50 px-3 py-2 text-sm"><b>{artist?.name ?? external?.preferred_name ?? "Unknown contributor"}</b><span className="ml-2 text-gray-500">{credit.role} · {credit.verification_status}</span></div>; })}</div>}<div className="grid gap-4 md:grid-cols-2"><div className="rounded-lg border p-3"><h3 className="mb-2 text-xs font-bold uppercase">Mangulina Artists</h3><AdminSearchPicker label="Artist" value={artistId} displayValue={artistName} placeholder="Search Artist…" endpoint="/api/admin/artists" resultKey="artists" onSelect={(option: PickerOption) => { setArtistId(option.id); setArtistName(option.name ?? "Artist"); setExternalId(""); setExternalName(""); }} onClear={() => { setArtistId(""); setArtistName(""); }} /></div><div className="rounded-lg border p-3"><h3 className="mb-2 text-xs font-bold uppercase">External Contributors</h3><AdminSearchPicker label="External Contributor" value={externalId} displayValue={externalName} placeholder="Search external identity…" endpoint="/api/admin/external-contributors" resultKey="external_contributors" onSelect={(option: PickerOption) => { setExternalId(option.id); setExternalName(option.title ?? "External Contributor"); setArtistId(""); setArtistName(""); }} onClear={() => { setExternalId(""); setExternalName(""); }} /><button className="mt-2 text-sm text-(--color-flagblue)" onClick={() => setShowExternalCreate(true)}>Add External Contributor</button></div></div><div className="mt-4 grid gap-3 md:grid-cols-[1fr_1fr_auto]"><select className={input} value={roleId} onChange={(event) => setRoleId(event.target.value)}><option value="">Choose contribution…</option>{workRoles.map((role) => <option key={role.id} value={role.id}>{role.display_name_en}</option>)}</select><input className={input} value={creditedAs} onChange={(event) => setCreditedAs(event.target.value)} placeholder="Credited as (optional)" /><button className={button} disabled={!hasIdentity || !roleId} onClick={() => void addCredit()}>Add credit</button></div>{creditAssertionId && <button className="mt-3 text-sm font-medium text-(--color-flagblue)" onClick={() => void act("credit.verify", { assertionId: creditAssertionId, reason: "Editor reviewed the supporting evidence." })}>Mark latest credit as reviewed</button>}</section>
      <section className={card}><div className="mb-4 flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-(--color-flagblue) text-sm text-white">4</span><div><h2 className="font-bold">Evidence</h2><p className="text-sm text-gray-500">Choose the sources that support the next credit or Recording link.</p></div></div><div className="space-y-2">{sources.map((source) => { const current = evidence.find((item) => item.sourceId === source.id); return <div key={source.id} className="flex flex-wrap items-center gap-3 rounded-lg border p-3"><div className="min-w-48 flex-1"><b>{source.title}</b><p className="text-xs text-gray-500">{source.source_type} · {source.visibility}</p></div><select className={`${input} max-w-48`} value={current?.relationship ?? ""} onChange={(event) => setEvidence((items) => [...items.filter((item) => item.sourceId !== source.id), ...(event.target.value ? [{ sourceId: source.id, relationship: event.target.value as Evidence["relationship"] }] : [])])}><option value="">Not selected</option><option value="supports">Supports</option><option value="disputes">Disputes</option><option value="contextualizes">Provides context</option></select></div>; })}</div><div className="mt-4 flex gap-2"><input className={input} value={sourceTitle} onChange={(event) => setSourceTitle(event.target.value)} placeholder="New source title" /><button className={button} disabled={!sourceTitle.trim()} onClick={async () => { const result = await act("source.create", { sourceType: "editorial_reference", title: sourceTitle, visibility: "internal" }); if (result?.source_id) setSourceTitle(""); }}>Add source</button></div></section>
      <section className={card}><div className="mb-4 flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-(--color-flagblue) text-sm text-white">5</span><div><h2 className="font-bold">Recorded versions</h2><p className="text-sm text-gray-500">Connect recordings that are performances of this song.</p></div></div><h3 className="text-xs font-bold uppercase text-gray-500">Linked Recordings</h3>{linkedRecordings.length ? <div className="mt-2 space-y-2">{linkedRecordings.map((recording) => { const artist = one(recording.artist); return <div key={recording.id} className="flex items-center justify-between gap-3 rounded-lg border bg-gray-50 p-3"><div><Link href={`/admin/catalog/recordings?recordingId=${recording.id}`} className="font-medium text-(--color-flagblue)">{recording.title}</Link><p className="text-xs text-gray-500">{artist?.name ?? "Unknown artist"}{recording.disambiguation ? ` · ${recording.disambiguation}` : ""}</p></div><button className="text-xs text-red-700" onClick={() => void act("work.unlink", { recordingId: recording.id, reason: "Editor requested that this Recording relationship return to unresolved." })}>Request unlink</button></div>; })}</div> : <p className="mt-2 rounded-lg border border-dashed bg-gray-50 p-3 text-sm text-gray-500">No Recordings linked yet.</p>}<h3 className="mb-2 mt-5 text-xs font-bold uppercase text-gray-500">Link another Recording</h3><div className="flex gap-3"><div className="flex-1"><AdminSearchPicker label="Unlinked Recording" value={recordingId} displayValue={recordingName} placeholder="Search Recordings…" endpoint="/api/admin/recordings" resultKey="recordings" onSelect={(option: PickerOption) => { setRecordingId(option.id); setRecordingName(option.title ?? "Recording"); }} onClear={() => { setRecordingId(""); setRecordingName(""); }} /></div><button className={`${button} self-end`} disabled={!recordingId} onClick={() => void linkRecording()}>Link Recording</button></div></section>
      <details className={card}><summary className="cursor-pointer font-bold text-(--color-flagblue)">Advanced editorial tools</summary><p className="mt-2 text-sm text-gray-500">Approvals, relationship history, and exceptional changes live here so they do not interrupt ordinary editing.</p><div className="mt-5"><h3 className="font-semibold">Pending approvals</h3>{approvals.length ? approvals.map((approval) => <div key={approval.id} className="mt-2 rounded-lg border p-3 text-sm"><b>{approval.decision_type}</b><p>{approval.reason}</p><div className="mt-2 flex gap-2"><button className={button} onClick={() => void act("decision.resolve", { decisionId: approval.id, resolution: "approve" })}>Approve</button><button className="rounded-lg border px-4 py-2" onClick={() => void act("decision.resolve", { decisionId: approval.id, resolution: "reject" })}>Reject</button></div></div>) : <p className="mt-2 text-sm text-gray-500">No pending approvals.</p>}</div><div className="mt-5"><button className="text-sm font-medium text-(--color-flagblue)" onClick={() => void loadHistory()}>Why is the selected Recording linked?</button>{history.map((event, index) => <div key={index} className="mt-2 rounded border p-3 text-sm"><b>{String(event.event_type)}</b><p>{String(event.reason ?? "")}</p><p className="text-xs text-gray-500">{String(event.occurred_at)}</p></div>)}</div></details></>}
    {showExternalCreate && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div role="dialog" aria-modal="true" aria-labelledby="external-title" className="w-full max-w-md space-y-3 rounded-xl bg-white p-5"><h2 id="external-title" className="text-xl font-bold">Add External Contributor</h2><input autoFocus className={input} value={newExternalName} onChange={(event) => setNewExternalName(event.target.value)} placeholder="Name *" /><input className={input} value={newExternalCountry} onChange={(event) => setNewExternalCountry(event.target.value)} placeholder="Country (optional)" /><div className="flex justify-end gap-2"><button className="rounded-lg border px-4 py-2" onClick={() => setShowExternalCreate(false)}>Cancel</button><button className={button} disabled={!newExternalName.trim()} onClick={() => void createExternalContributor()}>Create and select</button></div></div></div>}
  </div></main>;
}
