-- REVERT SCRIPT -- NOT A MIGRATION. Do not move this into
-- supabase/migrations/; nothing here should run automatically.
--
-- Restores artists.primary_genre and artists.genres to the values they held
-- before the 2026-08-22 genre normalisation pass. Use this only to undo that
-- work deliberately. It will also discard any genre edits made after that date.
--
-- The forward change is recorded in:
--   20260822010000_normalize_artist_primary_genre.sql
--   20260822020000_normalize_artist_genres_array.sql
-- Those encode the final state and cannot restore the originals; this can.
--
-- Reverting also reintroduces 131 values that match no row in `genres`,
-- which is what the forward pass existed to remove.

BEGIN;

WITH original(slug, primary_genre) AS (
    VALUES
      ('brandom-regino', 'other'),
      ('joa-el-super-mc', 'rap'),
      ('joly-sc', 'urban'),
      ('juan-francisco-garcia', 'classical'),
      ('lapiitoh-dangers', 'dembow'),
      ('carlos-manuel-vargas', 'classical'),
      ('ninon-lapeiretta-de-brouwer', 'classical'),
      ('adonis-produciendo', 'dembow'),
      ('keren-montero', 'other'),
      ('natti-natasha', 'reggaeton'),
      ('blackee-impala', 'trap'),
      ('nmnl', 'hip-hop'),
      ('domingo-philharmonic-orchestra', 'classical'),
      ('calor-urbano', 'urban'),
      ('el-alfa', 'dembow'),
      ('rochy-rd', 'dembow'),
      ('arrozito', 'urban'),
      ('jose-luis-hernandez-moreno', 'classical'),
      ('tunes', 'reggaeton'),
      ('redimi2', 'rap'),
      ('oasis-ministry', 'other'),
      ('marcos-yaroide', 'other'),
      ('amenazzy', 'reggaeton'),
      ('necro', 'hip-hop'),
      ('korven-brox', 'urban'),
      ('mc-wayne', 'urban'),
      ('twovm-para-cristo', 'reggaeton'),
      ('lizzy-parra', 'hip-hop'),
      ('chiky-bombom-la-pantera', 'urban'),
      ('dj-adoni', 'dembow'),
      ('tercer-cielo', 'other'),
      ('jezzy', 'rap'),
      ('shelow-shaq', 'urban'),
      ('david-appleton', 'classical'),
      ('j-a', 'dembow'),
      ('orquesta-sinfonica-nacional', 'classical'),
      ('jacinto-gimbernard', 'classical'),
      ('king-caballero', 'urban'),
      ('la-insuperable', 'urban'),
      ('flow-28', 'dembow'),
      ('messiah', 'trap'),
      ('beethoven-villaman', 'rap'),
      ('bs-el-ideologo', 'dembow'),
      ('kikito-black', 'urban'),
      ('nancy-amancio', 'other'),
      ('killer-rap', 'hip-hop'),
      ('r1-la-esencia', 'rap'),
      ('ghetto', 'dembow'),
      ('jeffrey-henriquez-rijo', 'urban'),
      ('francikario', 'hip-hop'),
      ('jesus-juan-antonio', 'classical'),
      ('puyalo-pantera', 'dembow'),
      ('emetede', 'urban'),
      ('kiko-el-crazy', 'dembow'),
      ('black-45-king', 'rap'),
      ('milka-la-mas-dura', 'dembow'),
      ('melymel', 'hip-hop'),
      ('rubinsky-rbk', 'rap'),
      ('luis-armando-rivera-gonzalez', 'classical'),
      ('la-materialista', 'urban'),
      ('aposento-alto', 'rap'),
      ('las-gemelas-fantasticas-rd', 'other'),
      ('dj-urba', 'reggaeton'),
      ('alex-linares', 'urban'),
      ('dj-joe-catador', 'dembow'),
      ('sammy-the-greatest', 'dembow'),
      ('shadow-blow', 'rap'),
      ('luny', 'reggaeton'),
      ('luna-drums', 'urban'),
      ('paramba', 'dembow'),
      ('eilyn-paulina', 'other'),
      ('gabriel-del-orbe', 'classical'),
      ('jairo-puello', 'other'),
      ('la-noe-aposento-alto', 'hip-hop'),
      ('angel-dior', 'dembow'),
      ('tokischa', 'reggaeton'),
      ('crisisromani', 'urban'),
      ('bulin-47', 'dembow'),
      ('inka', 'urban'),
      ('enmanuel-richarson', 'classical'),
      ('jabes', 'other'),
      ('indhira-rubiera', 'classical'),
      ('secreto-el-famoso-biberon', 'dembow'),
      ('bladimir-vasquez', 'urban'),
      ('ceky-viciny', 'dembow'),
      ('guillermo', 'other'),
      ('los-homeboys', 'hip-hop'),
      ('enrique-de-marchena', 'classical'),
      ('toqita', 'urban'),
      ('king-streetz', 'hip-hop'),
      ('anthony', 'urban'),
      ('jay-miky-flow', 'dembow'),
      ('don-miguelo', 'urban'),
      ('leo-rd', 'dembow'),
      ('quimico-ultra-mega', 'dembow'),
      ('musicologo-the-libro', 'urban'),
      ('young-grin', 'urban'),
      ('vakero', 'dembow'),
      ('dj-plano', 'dembow'),
      ('profeta-lirical', 'rap'),
      ('toxic-crow', 'rap'),
      ('jeyless', 'urban'),
      ('devin', 'urban'),
      ('adriel-sfx', 'urban'),
      ('donny-whey', 'urban'),
      ('barak', 'other'),
      ('jp-rmt', 'urban'),
      ('o-g-black', 'rap'),
      ('dary-hezz', 'urban'),
      ('j-noa', 'rap'),
      ('felipe-a-linares', 'other'),
      ('akinohayley', 'urban'),
      ('poeta-callejero', 'rap'),
      ('iris-franklyn', 'other'),
      ('proytecto-uno', 'rap'),
      ('tivi-gunz', 'urban'),
      ('bocatabu', 'pop'),
      ('charytin', 'pop'),
      ('alex-ferreira', 'pop'),
      ('sharlene', 'pop'),
      ('lenny-santana', 'pop'),
      ('leny', 'pop'),
      ('andres-rodriguez', 'pop'),
      ('mariangel', 'pop'),
      ('dj-arelis-hot', 'pop'),
      ('adriel-music', 'pop'),
      ('anais', 'pop'),
      ('rosangela-abreu', 'pop'),
      ('martha-heredia', 'pop'),
      ('abel', 'pop'),
      ('enerolisa-nunez', 'folklore')
)
UPDATE artists a SET primary_genre = o.primary_genre, updated_at = now()
FROM original o WHERE a.slug = o.slug AND a.primary_genre IS DISTINCT FROM o.primary_genre;

WITH original(slug, genres) AS (
    VALUES
      ('pirou-perez', ARRAY['jazz']::text[]),
      ('joly-sc', ARRAY['rap','dembow']::text[]),
      ('mc-wayne', ARRAY['hip hop']::text[]),
      ('palmer-hernandez', ARRAY['Salsa Romántica','Bachata']::text[]),
      ('rl-and-vanessa', ARRAY['merengue-urbano']::text[]),
      ('ovni-exp', ARRAY['urban-rap-hip-hop']::text[]),
      ('natan-el-profeta', ARRAY['merengue-urbano','urban-reggaeton','urban-rap-hip-hop']::text[]),
      ('martin-valoy', ARRAY['merengue']::text[]),
      ('mario-diaz', ARRAY['merengue','bachata','ballads']::text[]),
      ('don-miguelo', ARRAY['dembow','reggaeton']::text[]),
      ('juliana-o-neal', ARRAY['mambo']::text[]),
      ('ray-polanco', ARRAY['merengue-orquesta']::text[]),
      ('pavel-nunez', ARRAY['ballads']::text[]),
      ('dj-adoni', ARRAY['reggaeton','latin urban','merengue','bachata','salsa']::text[]),
      ('flow-28', ARRAY['urban']::text[]),
      ('bonny-cepeda', ARRAY['merengue-orquesta']::text[]),
      ('ghetto', ARRAY['urban','trap']::text[]),
      ('felix-del-rosario', ARRAY['jazz latino']::text[]),
      ('eddie-bastian', ARRAY['salsa-classic','bolero']::text[]),
      ('lilly-goodman', ARRAY['ballads','worship-gospel']::text[]),
      ('lapiitoh-dangers', ARRAY['urban']::text[]),
      ('kiko-el-crazy', ARRAY['urban']::text[]),
      ('nini-caffaro', ARRAY['latin pop','ballads-bolero']::text[]),
      ('damiron', ARRAY['folclor dominicano']::text[]),
      ('manuel-de-jesus-jimenez-ortega', ARRAY['Bachata','Balada','Son']::text[]),
      ('jay-miky-flow', ARRAY['urban','reggaeton']::text[]),
      ('joa-el-super-mc', ARRAY['hip-hop','urban']::text[]),
      ('beethoven-villaman', ARRAY['hip-hop','urban']::text[]),
      ('nmnl', ARRAY['urban']::text[]),
      ('july-mateo-rasputin', ARRAY['merengue-orquesta']::text[]),
      ('adonis-produciendo', ARRAY['urban','reggaeton','producer']::text[]),
      ('twovm-para-cristo', ARRAY['urban contemporary']::text[]),
      ('jankobow', ARRAY['urban']::text[]),
      ('natti-natasha', ARRAY['bachata','latin pop','urban']::text[]),
      ('juan-francisco-garcia', ARRAY['académica','folclor']::text[]),
      ('omega', ARRAY['Mambo','merengue']::text[]),
      ('carlos-manuel-vargas', ARRAY['chamber music','latin american classical','dominican classical']::text[]),
      ('blackee-impala', ARRAY['urban']::text[]),
      ('mario-de-jesus-baez', ARRAY['Cumbia','Salsa','Merengue']::text[]),
      ('banda-real', ARRAY['folklore']::text[]),
      ('andre-parra-marte', ARRAY['alternative','acoustic']::text[]),
      ('jose-bello', ARRAY['son']::text[]),
      ('ninon-lapeiretta-de-brouwer', ARRAY['instrumental-classical']::text[]),
      ('el-alfa', ARRAY['urban','reggaeton']::text[]),
      ('domingo-philharmonic-orchestra', ARRAY['symphonic','instrumental']::text[]),
      ('joseito-mateo', ARRAY['bolero']::text[]),
      ('jose-luis-hernandez-moreno', ARRAY['académica']::text[]),
      ('el-prodigio', ARRAY['jazz latino','merengue','merengue-perico-ripiao']::text[]),
      ('arrozito', ARRAY['comedy']::text[]),
      ('deyvi-sime', ARRAY['jazz latino']::text[]),
      ('alberto-plata', ARRAY['folklore']::text[]),
      ('mula', ARRAY['urbano','electronic']::text[]),
      ('martha-candela', ARRAY['merengue-urbano','merengue-mambo']::text[]),
      ('cuco-valoy', ARRAY['Son Dominicano']::text[]),
      ('jorge-luis-rosario-rodriguez', ARRAY['académica']::text[]),
      ('luis-armando-rivera-gonzalez', ARRAY['Merengue','Bolero','Zarzuela']::text[]),
      ('dioris-valladares', ARRAY['bolero']::text[]),
      ('keren-montero', ARRAY['adoracion']::text[]),
      ('manuel-simo', ARRAY['Classical']::text[]),
      ('reychesta-secret-weapon', ARRAY['Rap / Hip Hop']::text[]),
      ('daniel-santacruz', ARRAY['pop latino','merengue','kizomba']::text[]),
      ('eilyn-paulina', ARRAY['adoración']::text[]),
      ('richie-cepeda', ARRAY['merengue']::text[]),
      ('adalgisa-pantaleon', ARRAY['merengue','bachata','tropical','bolero']::text[]),
      ('luis-pimentel', ARRAY['traditional']::text[]),
      ('nelson-estevez', ARRAY['bachata']::text[]),
      ('kilvin-pena', ARRAY['salsa']::text[]),
      ('marcos-yaroide', ARRAY['latin pop']::text[]),
      ('amenazzy', ARRAY['r&b latino','urban']::text[]),
      ('necro', ARRAY['urban']::text[]),
      ('lenny-santana', ARRAY['romantic']::text[]),
      ('ala-jaza', ARRAY['bachata','merengue-urbano','merengue-mambo']::text[]),
      ('xiomara-fortuna', ARRAY['jazz','folk music']::text[]),
      ('gangrena-cerebral', ARRAY['grindcore','metal']::text[]),
      ('jose-manuel-calderon', ARRAY['bolero']::text[]),
      ('monkey-black', ARRAY['dembow','urban']::text[]),
      ('alex-ferreira', ARRAY['indie folk','tropical alternative']::text[]),
      ('sharlene', ARRAY['pop']::text[]),
      ('andres-rodriguez', ARRAY['acoustic','ballad']::text[]),
      ('juan-bautista-alfonseca', ARRAY['classical','folclor']::text[]),
      ('fausto-rey', ARRAY['bolero','merengue']::text[]),
      ('lolo-en-el-microfono', ARRAY['urban']::text[]),
      ('daniel-moncion', ARRAY['pop latino']::text[]),
      ('anthony-carino', ARRAY['folklore']::text[]),
      ('bocatabu', ARRAY['alternative rock','indie']::text[]),
      ('brandom-regino', ARRAY['pop','worship']::text[]),
      ('amarfis-y-la-banda-de-atakke', ARRAY['mambo','merengue']::text[]),
      ('los-sufridos', ARRAY['bachata']::text[]),
      ('lizzy-parra', ARRAY['urban','christian']::text[]),
      ('andre-veloz', ARRAY['bolero']::text[]),
      ('johnny-pacheco', ARRAY['son','guaguancó']::text[]),
      ('la-armada', ARRAY['urban']::text[]),
      ('expresion-joven', ARRAY['trova','folk']::text[]),
      ('mario-rivera', ARRAY['Jazz','Salsa','Merengue Jazz']::text[]),
      ('chris-alflow', ARRAY['Dembow']::text[]),
      ('jezzy', ARRAY['hip-hop','urban']::text[]),
      ('josean-jacobo', ARRAY['Jazz','Afro-Dominican Jazz','Fusion']::text[]),
      ('janina-rosado', ARRAY['merengue','bachata','jazz','fusion']::text[]),
      ('luis-terror-dias', ARRAY['folklore','fusion','merengue','bachata']::text[]),
      ('david-appleton', ARRAY['fusión','cinematic']::text[]),
      ('el-cherry-scom', ARRAY['urban','reggaeton']::text[]),
      ('j-a', ARRAY['urban']::text[]),
      ('dj-scuff', ARRAY['hip hop','rap','dembow','reggaeton','trap']::text[]),
      ('grunjeo', ARRAY['alternative']::text[]),
      ('ilegales', ARRAY['pop latino','urban']::text[]),
      ('donaty', ARRAY['urban']::text[]),
      ('jacinto-gimbernard', ARRAY['académica']::text[]),
      ('johnny-chocolate', ARRAY['salsa']::text[]),
      ('king-caballero', ARRAY['alternative']::text[]),
      ('jonatan-pina-duluc', ARRAY['fusion','rock']::text[]),
      ('el-fecho-rd', ARRAY['urban']::text[]),
      ('la-insuperable', ARRAY['dembow']::text[]),
      ('hector-acosta-el-torito', ARRAY['bachata']::text[]),
      ('maria-diaz', ARRAY['merengue','merengue-perico-ripiao']::text[]),
      ('angela-carrasco', ARRAY['pop-latin-pop','ballads-romantic','merengue']::text[]),
      ('enerolisa-nunez', ARRAY['salve']::text[]),
      ('messiah', ARRAY['urban','hip hop']::text[]),
      ('23thierno', ARRAY['latin trap','urban']::text[]),
      ('moria', ARRAY['urbano','urban-dembow']::text[]),
      ('mr-yeison', ARRAY['Dembow']::text[]),
      ('dario-estrella', ARRAY['merengue','fusión']::text[]),
      ('antony-santos', ARRAY['bachata-romantica','merengue-perico-ripiao']::text[]),
      ('bs-el-ideologo', ARRAY['urban','trap']::text[]),
      ('killer-rap', ARRAY['urban']::text[]),
      ('nancy-amancio', ARRAY['balada','pop']::text[]),
      ('jeffrey-henriquez-rijo', ARRAY['académica','bachata','reggaeton']::text[]),
      ('francikario', ARRAY['rap','urban']::text[]),
      ('vicente-garcia', ARRAY['world music','music of the Caribbean','merengue','alternative music','reggae']::text[]),
      ('frank-cruz', ARRAY['bolero']::text[]),
      ('juan-hidalgo', ARRAY['bachata']::text[]),
      ('jesus-juan-antonio', ARRAY['académica']::text[]),
      ('manny-cruz', ARRAY['latin pop','bachata']::text[]),
      ('frecox-unic', ARRAY['trap']::text[]),
      ('gda-el-unico', ARRAY['dembow']::text[]),
      ('grupo-extra', ARRAY['pop latino']::text[]),
      ('jandy-feliz', ARRAY['pop latino']::text[]),
      ('mamajuana', ARRAY['House']::text[]),
      ('genoveva-la-patrona', ARRAY['latin','merengue','reggaeton']::text[]),
      ('aridia-ventura', ARRAY['folklore']::text[]),
      ('henry-santos', ARRAY['urban']::text[]),
      ('luigui-bleand', ARRAY['afrobeat','Rap / Hip Hop']::text[]),
      ('juan-luis-guerra', ARRAY['bachata','fusion']::text[]),
      ('emetede', ARRAY['dembow']::text[]),
      ('alex-matos', ARRAY['balada']::text[]),
      ('alejandro-torrens', ARRAY['pop latino','bolero']::text[]),
      ('leny', ARRAY['pop']::text[]),
      ('black-45-king', ARRAY['hip-hop','urban']::text[]),
      ('felix-cumbe', ARRAY['bachata']::text[]),
      ('pochy-y-su-cocoband', ARRAY['merengue-orquesta']::text[]),
      ('los-toros-band', ARRAY['bachata']::text[]),
      ('milka-la-mas-dura', ARRAY['urban']::text[]),
      ('francisco-casanova', ARRAY['lírico']::text[]),
      ('lapiz-conciente', ARRAY['urban']::text[]),
      ('anon-muller', ARRAY['indie']::text[]),
      ('melymel', ARRAY['rap','urban']::text[]),
      ('dj-mari-d', ARRAY['latin','hip hop','open format','club','dance']::text[]),
      ('rubinsky-rbk', ARRAY['Christian hip-hop','reggaeton']::text[]),
      ('antidoto-casero', ARRAY['alternative','reggae']::text[]),
      ('la-materialista', ARRAY['pop','dembow']::text[]),
      ('morbid', ARRAY['rock']::text[]),
      ('aposento-alto', ARRAY['hip-hop','urban']::text[]),
      ('averly-morillo', ARRAY['ballads']::text[]),
      ('mickey-dastinz', ARRAY['hip hop']::text[]),
      ('maridalia-hernandez', ARRAY['merengue','bachata']::text[]),
      ('las-gemelas-fantasticas-rd', ARRAY['adoracion']::text[]),
      ('ramon-torres', ARRAY['tropical music']::text[]),
      ('luis-pimentel-y-su-conjunto-de-estrellas', ARRAY['traditional']::text[]),
      ('rafael-solano', ARRAY['Bolero','Merengue','Folk']::text[]),
      ('el-cata', ARRAY['urban']::text[]),
      ('apofis-imn', ARRAY['rap underground','urban']::text[]),
      ('negrito-chapuseaux', ARRAY['bolero','son','merengue']::text[]),
      ('dj-urba', ARRAY['urban']::text[]),
      ('nino-freestyle', ARRAY['urban','Rap / Hip Hop']::text[]),
      ('merged-juan-luis-guerra-440', ARRAY['bachata','fusion']::text[]),
      ('alex-linares', ARRAY['comedy']::text[]),
      ('dj-joe-catador', ARRAY['latin urban','reggaeton']::text[]),
      ('sammy-the-greatest', ARRAY['latin urban','reggaeton']::text[]),
      ('chimbala', ARRAY['reggaeton','urbano music','urban contemporary','Dembow']::text[]),
      ('nico-clinico', ARRAY['reggaeton']::text[]),
      ('juan-colon', ARRAY['jazz latino']::text[]),
      ('bienvenido-brens', ARRAY['merengue']::text[]),
      ('michel-camilo', ARRAY['Jazz','Clásica','Classical']::text[]),
      ('musiquito', ARRAY['merengue']::text[]),
      ('raquel-arias', ARRAY['worship']::text[]),
      ('johandy-urena', ARRAY['fusion']::text[]),
      ('la-baby', ARRAY['urban','Dembow']::text[]),
      ('luny', ARRAY['urban']::text[]),
      ('indigo', ARRAY['pop','alternative']::text[]),
      ('luna-drums', ARRAY['percussion']::text[]),
      ('antihippie', ARRAY['punk','indie','urban','rock']::text[]),
      ('jorge-morel', ARRAY['académica']::text[]),
      ('aisha-syed-castro', ARRAY['instrumental-classical']::text[]),
      ('jorge-taveras', ARRAY['balada']::text[]),
      ('dominic', ARRAY['salsa']::text[]),
      ('gabriel-del-orbe', ARRAY['Romanticismo']::text[]),
      ('jose-antonio-rodriguez', ARRAY['balada','canción de autor']::text[]),
      ('blas-duran', ARRAY['merengue de guataca']::text[]),
      ('maffio', ARRAY['reggaeton','latin pop','merengue','bachata']::text[]),
      ('adriano-ventura', ARRAY['folklore']::text[]),
      ('jairo-puello', ARRAY['gospel','christian pop']::text[]),
      ('luys-bien', ARRAY['bachata','bolero','salsa','pambiche','latin']::text[]),
      ('dj-arelis-hot', ARRAY['soul','urban','rap','hip hop','reggaeton romantico','merengue']::text[]),
      ('la-noe-aposento-alto', ARRAY['christian rap','latin hip hop','latin urban']::text[]),
      ('bryan-dotel', ARRAY['ballad','acoustic']::text[]),
      ('adriel-music', ARRAY['r&b','urban']::text[]),
      ('angel-dior', ARRAY['urban']::text[]),
      ('mozart-la-para', ARRAY['rap','reggaeton','urban','urban-rap-hip-hop']::text[]),
      ('juan-lanfranco', ARRAY['merengue']::text[]),
      ('carlos-alfredo-fatule', ARRAY['merengue','musical theatre']::text[]),
      ('juan-francisco-ordonez', ARRAY['rock alternativo','jazz latino','bachata']::text[]),
      ('manuel-miller', ARRAY['dance','house','afro house','latin electronic','techno']::text[]),
      ('ito-ogamy', ARRAY['Rap / Hip Hop']::text[]),
      ('gior-chambonea', ARRAY['urban']::text[]),
      ('oscar-micheli', ARRAY['jazz']::text[]),
      ('oscar-dominic', ARRAY['ballads']::text[]),
      ('luis-aquino', ARRAY['salsa','pop']::text[]),
      ('eklectico', ARRAY['dembow','alternative','urban-rap-hip-hop']::text[]),
      ('freddy-antonio-sarante-perdomo', ARRAY['merengue']::text[]),
      ('yovanny-polanco', ARRAY['Perico Ripiao']::text[]),
      ('fair-trade', ARRAY['alternative']::text[]),
      ('henry-garcia', ARRAY['salsa']::text[]),
      ('tokischa', ARRAY['Dominican dembow','diva house','dancehall']::text[]),
      ('karlos-rose', ARRAY['urban']::text[]),
      ('luis-caracter', ARRAY['traditional']::text[]),
      ('bulin-47', ARRAY['urban','comedy']::text[]),
      ('milly-quezada', ARRAY['bachata']::text[]),
      ('inka', ARRAY['hip-hop','rap']::text[]),
      ('elenita-santos', ARRAY['merengue']::text[]),
      ('cocolo-rd', ARRAY['urban-dembow']::text[]),
      ('haraca-kiko', ARRAY['urban','Dembow']::text[]),
      ('enmanuel-richarson', ARRAY['instrumental']::text[]),
      ('alfredo-polonia', ARRAY['folklore']::text[]),
      ('hollywood', ARRAY['pop','alternative']::text[]),
      ('jabes', ARRAY['gospel','pop']::text[]),
      ('orquesta-la-muralla', ARRAY['merengue']::text[]),
      ('albertino-graciano', ARRAY['folklore']::text[]),
      ('alberto-beltran', ARRAY['merengue','guaracha']::text[]),
      ('draconum-oth', ARRAY['metal','alternative']::text[]),
      ('la-pajarita-la-paul', ARRAY['dembow']::text[]),
      ('indhira-rubiera', ARRAY['lírico']::text[]),
      ('anais', ARRAY['ballad']::text[]),
      ('bladimir-vasquez', ARRAY['reggaeton']::text[]),
      ('secreto-el-famoso-biberon', ARRAY['reggaeton','urban merengue']::text[]),
      ('alex-bueno', ARRAY['bachata','salsa','bolero','ballads']::text[]),
      ('fritz-abreu', ARRAY['fusion']::text[]),
      ('antonio-vasquez', ARRAY['folklore']::text[]),
      ('luis-kalaff', ARRAY['bolero','traditional','salve']::text[]),
      ('lucien-le-grub', ARRAY['alternative']::text[]),
      ('fernando-soriano', ARRAY['bachata']::text[]),
      ('guillermo', ARRAY['adoración']::text[]),
      ('jose-rufino-reyes-y-siancas', ARRAY['sacra']::text[]),
      ('nelson-de-la-olla', ARRAY['merengue']::text[]),
      ('orquesta-in-art', ARRAY['jazz']::text[]),
      ('los-homeboys', ARRAY['merenhouse','urban']::text[]),
      ('kalimete', ARRAY['urban']::text[]),
      ('blackfox', ARRAY['indie']::text[]),
      ('martha-heredia', ARRAY['r&b','reggaeton']::text[]),
      ('papaa-tyga', ARRAY['urbano','urban-dembow']::text[]),
      ('hancel-osorius', ARRAY['classical']::text[]),
      ('dj-gabriel-b', ARRAY['latin urban','dembow']::text[]),
      ('enrique-de-marchena', ARRAY['romántico','classical']::text[]),
      ('teodoro-reyes', ARRAY['bachata']::text[]),
      ('archaios', ARRAY['alternative']::text[]),
      ('fernando-echavarria', ARRAY['son','merengue']::text[]),
      ('king-streetz', ARRAY['urban']::text[]),
      ('los-congos-del-espiritu-santo', ARRAY['afro-dominican','traditional']::text[]),
      ('la-india-canela', ARRAY['merengue','merengue-perico-ripiao']::text[]),
      ('gabriel-pagan', ARRAY['pop latino']::text[]),
      ('leo-rd', ARRAY['urban']::text[]),
      ('abel', ARRAY['ballad']::text[]),
      ('fernando-villalona', ARRAY['bolero','balada']::text[]),
      ('derick-daniel-perez-cordero', ARRAY['fusión']::text[]),
      ('musicologo-the-libro', ARRAY['reggaeton','hip hop']::text[]),
      ('mickey-taveras', ARRAY['merengue','bachata','latin pop']::text[]),
      ('sandy-gabriel', ARRAY['Latin Jazz','Fusion']::text[]),
      ('esme', ARRAY['pop latino']::text[]),
      ('dj-plano', ARRAY['latin urban']::text[]),
      ('los-ahijados', ARRAY['bolero']::text[]),
      ('manuel-tejada', ARRAY['latin pop']::text[]),
      ('jeyless', ARRAY['pop']::text[]),
      ('alexandra-queen', ARRAY['Romantic']::text[]),
      ('devin', ARRAY['bachata','pop latino']::text[]),
      ('adriel-sfx', ARRAY['instrumental','experimental']::text[]),
      ('petiton-guzman', ARRAY['instrumental-classical']::text[]),
      ('donny-whey', ARRAY['dembow','reggaeton']::text[]),
      ('jodio-loco-sucio', ARRAY['punk','alternative','funk rock']::text[]),
      ('irka-mateo', ARRAY['world music','fusion']::text[]),
      ('jp-rmt', ARRAY['rap']::text[]),
      ('barak', ARRAY['musica cristiana','pop rock']::text[]),
      ('bullumba-landestoy', ARRAY['classical']::text[]),
      ('dary-hezz', ARRAY['dembow','reggaeton']::text[]),
      ('j-noa', ARRAY['hip-hop','urban']::text[]),
      ('leonor-porcella-de-brea', ARRAY['Bolero','Pop Latino']::text[]),
      ('jc', ARRAY['trap']::text[]),
      ('egleyda-belliard', ARRAY['pop latino','adoración']::text[]),
      ('alex-diaz', ARRAY['latin jazz','merengue']::text[]),
      ('papi-sanchez', ARRAY['urban-rap-hip-hop']::text[]),
      ('hector-santana', ARRAY['jazz latino']::text[]),
      ('jhoni-the-voice', ARRAY['urban']::text[]),
      ('emil-cerda', ARRAY['experimental','ambient']::text[]),
      ('jose-batista-fuchi', ARRAY['folclor']::text[]),
      ('felipe-a-linares', ARRAY['choral','adoración']::text[]),
      ('anthony-rios', ARRAY['bolero','merengue','bachata']::text[]),
      ('el-trio', ARRAY['son']::text[]),
      ('amarfis', ARRAY['mambo']::text[]),
      ('joan-soriano', ARRAY['world music']::text[]),
      ('fortuna-la-super-f', ARRAY['urban','Reggaeton']::text[]),
      ('alih-jey', ARRAY['indie pop','latin pop']::text[]),
      ('akinohayley', ARRAY['r&b','alternative','rap']::text[]),
      ('luis-alberti', ARRAY['bolero','traditional','big-band']::text[]),
      ('luny-tunes', ARRAY['latin urban','bachaton','latin']::text[]),
      ('iris-franklyn', ARRAY['adoración']::text[]),
      ('raulin-rodriguez', ARRAY['bachata-romantica']::text[]),
      ('lismar', ARRAY['urban','dembow','Drill']::text[]),
      ('bartolito-y-los-bravos-del-son', ARRAY['afro-cuban']::text[]),
      ('duluc', ARRAY['fusión','rock']::text[])
)
UPDATE artists a SET genres = o.genres, updated_at = now()
FROM original o WHERE a.slug = o.slug AND a.genres IS DISTINCT FROM o.genres;

COMMIT;
