BEGIN;

-- Restore editorial_entity_references rows for artistReference nodes that had
-- none. Each such node made the renderer fall back to plain text: resolve.ts
-- returns isPubliclyLinkable:false on a missing relation, and
-- ArtistReference.tsx then prints the display text instead of a link. These
-- mentions read as links in the prose but were inert on the public site.
--
-- target_artist_id is set to the node's own attrs.artistId. resolve.ts treats
-- any other value as a blocking target_mismatch, so the node's own attribute
-- is the only correct source; nothing here is inferred from the display text.
--
-- 76 rows across 26 documents.
--
-- Generated by tools/editorial/fixOrphanedReferences.mts, enumerating nodes
-- through allEditorialInlineNodes over a validated document — the same path
-- resolve.ts uses, so this matches what the renderer sees.

INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('8cb3a608-d0aa-4ecb-8172-f26f0bc6e10d', '4b560cbb-aa59-445c-904a-29dcc2e2cd28', 'artist', '3f8bafec-e5ee-415d-8405-9551cceeeb9b');  -- Milly Quezada (en) -> Johnny Ventura
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('be9e8ccf-0032-4189-be7f-717282da1dd4', 'dcd5bb91-4056-4fa7-85f1-4ad83ea64e12', 'artist', '10034596-47cb-46ba-9e80-9ea319a2c0df');  -- Maridalia Hernández (en) -> Juan Luis Guerra
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('be9e8ccf-0032-4189-be7f-717282da1dd4', '8af21aa1-c3f6-4bdb-b125-eb3fd4e93ca2', 'artist', '4d3a653c-688e-47c1-8cec-b8cf85a4abac');  -- Maridalia Hernández (en) -> Manuel Tejada
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('be9e8ccf-0032-4189-be7f-717282da1dd4', 'd7121546-d00a-4af0-9f36-942ad23536b9', 'artist', '10034596-47cb-46ba-9e80-9ea319a2c0df');  -- Maridalia Hernández (en) -> Juan Luis Guerra
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('be9e8ccf-0032-4189-be7f-717282da1dd4', 'a778140b-531d-4911-bead-90154e4bec5e', 'artist', '4d3a653c-688e-47c1-8cec-b8cf85a4abac');  -- Maridalia Hernández (en) -> Manuel Tejada
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('be9e8ccf-0032-4189-be7f-717282da1dd4', 'f5cc61e4-fb3b-4a1d-b87a-9116b54ecd28', 'artist', '02f23257-1cf6-4a4c-8df1-1f9aa630a2c3');  -- Maridalia Hernández (en) -> Ramón Orlando
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('be9e8ccf-0032-4189-be7f-717282da1dd4', '23a63c8f-aa0a-40c4-a84f-7ff4e5f283c9', 'artist', '9333da06-ad03-44eb-9b81-c21d0ccdd0ea');  -- Maridalia Hernández (en) -> Fefita La Grande
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('be9e8ccf-0032-4189-be7f-717282da1dd4', 'c4e1efb1-dc75-469c-91a6-21640f95ecb4', 'artist', '10034596-47cb-46ba-9e80-9ea319a2c0df');  -- Maridalia Hernández (en) -> Juan Luis Guerra
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('554caa7f-3342-4202-bf3d-2cbee4b18548', '6c0c1f68-5d8e-4a35-b559-54aee31b302f', 'artist', '3f8bafec-e5ee-415d-8405-9551cceeeb9b');  -- Crispín Fernández (en) -> Johnny Ventura
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('554caa7f-3342-4202-bf3d-2cbee4b18548', '4d04f819-bfb4-4cb1-8b64-59655ec6ef90', 'artist', '059a9e99-5d11-433e-97b9-9c35e57908f1');  -- Crispín Fernández (en) -> Sergio Vargas
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('554caa7f-3342-4202-bf3d-2cbee4b18548', 'b5594a3e-8a88-4b33-9d0c-7bc07f66a75b', 'artist', '02f23257-1cf6-4a4c-8df1-1f9aa630a2c3');  -- Crispín Fernández (en) -> Ramón Orlando
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('554caa7f-3342-4202-bf3d-2cbee4b18548', 'aad87bec-591a-4822-989e-371151784038', 'artist', '10034596-47cb-46ba-9e80-9ea319a2c0df');  -- Crispín Fernández (en) -> Juan Luis Guerra
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('554caa7f-3342-4202-bf3d-2cbee4b18548', 'e4cd0135-9abf-4d96-a796-0dadbdc1eb41', 'artist', '3f8bafec-e5ee-415d-8405-9551cceeeb9b');  -- Crispín Fernández (en) -> Johnny Ventura
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('554caa7f-3342-4202-bf3d-2cbee4b18548', 'b6fba039-60ad-4857-b06a-b86efaf6538c', 'artist', '3f8bafec-e5ee-415d-8405-9551cceeeb9b');  -- Crispín Fernández (en) -> Johnny Ventura
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('554caa7f-3342-4202-bf3d-2cbee4b18548', 'e437dd3a-a402-41fb-b27f-ab2b30eba5e2', 'artist', '059a9e99-5d11-433e-97b9-9c35e57908f1');  -- Crispín Fernández (en) -> Sergio Vargas
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('554caa7f-3342-4202-bf3d-2cbee4b18548', 'bfc06686-ac2a-4882-93fe-0db1c1881275', 'artist', '02f23257-1cf6-4a4c-8df1-1f9aa630a2c3');  -- Crispín Fernández (en) -> Ramón Orlando
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('554caa7f-3342-4202-bf3d-2cbee4b18548', '7c691c7d-a58a-4ca0-bf3f-d6f828182190', 'artist', '10034596-47cb-46ba-9e80-9ea319a2c0df');  -- Crispín Fernández (en) -> Juan Luis Guerra
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('ec23852d-ea99-49b9-a75b-36d7ceacbd29', 'a292d2ee-ab07-4ade-b05f-5989018eec65', 'artist', '3f8bafec-e5ee-415d-8405-9551cceeeb9b');  -- Crispín Fernández (es) -> Johnny Ventura
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('ec23852d-ea99-49b9-a75b-36d7ceacbd29', 'cd36bfe9-ec33-4606-967c-d9b437b7ebff', 'artist', '059a9e99-5d11-433e-97b9-9c35e57908f1');  -- Crispín Fernández (es) -> Sergio Vargas
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('ec23852d-ea99-49b9-a75b-36d7ceacbd29', '894270f0-fb83-457d-9c21-1c5da4d810db', 'artist', '02f23257-1cf6-4a4c-8df1-1f9aa630a2c3');  -- Crispín Fernández (es) -> Ramón Orlando
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('ec23852d-ea99-49b9-a75b-36d7ceacbd29', '540641fb-f80e-43e3-8bc1-c6450d2169b2', 'artist', '10034596-47cb-46ba-9e80-9ea319a2c0df');  -- Crispín Fernández (es) -> Juan Luis Guerra
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('ec23852d-ea99-49b9-a75b-36d7ceacbd29', '9279f991-099b-4607-994e-b9ad761bf12a', 'artist', '3f8bafec-e5ee-415d-8405-9551cceeeb9b');  -- Crispín Fernández (es) -> Johnny Ventura
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('ec23852d-ea99-49b9-a75b-36d7ceacbd29', '9eb0d69d-d63d-4bbd-8ab3-6512a0df0419', 'artist', '3f8bafec-e5ee-415d-8405-9551cceeeb9b');  -- Crispín Fernández (es) -> Johnny Ventura
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('ec23852d-ea99-49b9-a75b-36d7ceacbd29', '842ac717-0910-469e-849f-9ccce6919ca1', 'artist', '059a9e99-5d11-433e-97b9-9c35e57908f1');  -- Crispín Fernández (es) -> Sergio Vargas
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('ec23852d-ea99-49b9-a75b-36d7ceacbd29', 'dffb6454-ba1d-42ad-8197-3c76983a4d52', 'artist', '02f23257-1cf6-4a4c-8df1-1f9aa630a2c3');  -- Crispín Fernández (es) -> Ramón Orlando
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('ec23852d-ea99-49b9-a75b-36d7ceacbd29', '1b3e46c4-7f2f-4b1e-ae9a-5ed05176f106', 'artist', '10034596-47cb-46ba-9e80-9ea319a2c0df');  -- Crispín Fernández (es) -> Juan Luis Guerra
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('88889428-b468-41ad-9357-af5dc71a7f70', 'b99bc6b6-ec34-48d9-846b-70419c07cfeb', 'artist', '4d3a653c-688e-47c1-8cec-b8cf85a4abac');  -- Alex Bueno (en) -> Manuel Tejada
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('88889428-b468-41ad-9357-af5dc71a7f70', 'a38a2a94-a713-460d-b9e3-b924e6bbb4be', 'artist', '02f23257-1cf6-4a4c-8df1-1f9aa630a2c3');  -- Alex Bueno (en) -> Ramón Orlando
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('0a41757e-2f6a-4916-a1f2-5f2dc14125b2', '76f4611d-2dc2-4edc-a30c-f57c3072b5db', 'artist', '9c02d1a1-952e-4855-9b60-c0266236378d');  -- Dalvin la Melodía (en) -> Prince Royce
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('0a41757e-2f6a-4916-a1f2-5f2dc14125b2', 'ee0bb9c6-9413-43b1-8206-684a55e6f3b9', 'artist', 'a77079ce-351a-4eb5-baef-de02dc1b62ce');  -- Dalvin la Melodía (en) -> Zacarías Ferreira
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('ee5a46f3-9387-4271-8db8-b4cb15c1c90a', 'a3654339-ed3b-4e3d-b1bf-41eca7d02c65', 'artist', '9c02d1a1-952e-4855-9b60-c0266236378d');  -- Dalvin la Melodía (es) -> Prince Royce
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('ee5a46f3-9387-4271-8db8-b4cb15c1c90a', 'b47b2c36-e36b-48e1-b734-c709c4587593', 'artist', 'a77079ce-351a-4eb5-baef-de02dc1b62ce');  -- Dalvin la Melodía (es) -> Zacarías Ferreira
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('1dfac941-17a2-43e7-9f29-0283f56ca4b7', '363c4cdf-15e6-4b28-bd05-ba00e8fd3e60', 'artist', '4d3a653c-688e-47c1-8cec-b8cf85a4abac');  -- Alex Bueno (es) -> Manuel Tejada
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('62300e59-1cb5-43c3-8be7-2611bd9aadbe', 'f8577536-3d61-462e-ae45-6c846140acaa', 'artist', '2bc36959-dcce-4e10-9ecf-2cd418eaa489');  -- Peter Cruz (en) -> Wilfrido Vargas
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('62300e59-1cb5-43c3-8be7-2611bd9aadbe', '5197db54-8ce9-410c-96b3-2095223b503c', 'artist', '2bc36959-dcce-4e10-9ecf-2cd418eaa489');  -- Peter Cruz (en) -> Wilfrido Vargas
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('62300e59-1cb5-43c3-8be7-2611bd9aadbe', 'de80cd9f-8faf-4825-ac94-9cae27a9ed4d', 'artist', '2bc36959-dcce-4e10-9ecf-2cd418eaa489');  -- Peter Cruz (en) -> Wilfrido Vargas
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('62300e59-1cb5-43c3-8be7-2611bd9aadbe', '6d8eea88-b067-48b6-a716-19b55cb58a6d', 'artist', '02f23257-1cf6-4a4c-8df1-1f9aa630a2c3');  -- Peter Cruz (en) -> Ramón Orlando
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('62300e59-1cb5-43c3-8be7-2611bd9aadbe', '11d06959-40dd-4037-96bd-9d736b0f97bd', 'artist', '02f23257-1cf6-4a4c-8df1-1f9aa630a2c3');  -- Peter Cruz (en) -> Ramón Orlando
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('aa456ca4-c0a5-4171-a646-73f3315dea5e', 'c7c39f36-9191-433e-ac6f-1f2fe697cc67', 'artist', '2bc36959-dcce-4e10-9ecf-2cd418eaa489');  -- Peter Cruz (es) -> Wilfrido Vargas
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('aa456ca4-c0a5-4171-a646-73f3315dea5e', '3195cacd-0cd1-48e7-abc6-ede4469c7927', 'artist', '2bc36959-dcce-4e10-9ecf-2cd418eaa489');  -- Peter Cruz (es) -> Wilfrido Vargas
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('aa456ca4-c0a5-4171-a646-73f3315dea5e', 'f9df6100-63f3-45c8-a73f-6e979d01cf3d', 'artist', '2bc36959-dcce-4e10-9ecf-2cd418eaa489');  -- Peter Cruz (es) -> Wilfrido Vargas
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('aa456ca4-c0a5-4171-a646-73f3315dea5e', 'd123752f-07d0-4e2f-8a3a-223885c84a84', 'artist', '2bc36959-dcce-4e10-9ecf-2cd418eaa489');  -- Peter Cruz (es) -> Wilfrido Vargas
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('aa456ca4-c0a5-4171-a646-73f3315dea5e', '0f114436-8a66-492b-948a-02c1cc9987d3', 'artist', '2bc36959-dcce-4e10-9ecf-2cd418eaa489');  -- Peter Cruz (es) -> Wilfrido Vargas
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('aa456ca4-c0a5-4171-a646-73f3315dea5e', 'd6162485-354d-4e67-bb78-e6fc6dce2e3c', 'artist', '02f23257-1cf6-4a4c-8df1-1f9aa630a2c3');  -- Peter Cruz (es) -> Ramón Orlando
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('029ab794-f307-4ffa-ab6e-ce9a41084422', 'ce1a0a5e-cf5e-4f7e-ab4f-d78cbf68d366', 'artist', '2bc36959-dcce-4e10-9ecf-2cd418eaa489');  -- Fernando Villalona (en) -> Wilfrido Vargas
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('1971d182-412a-4686-95a9-babdec4cc738', '1e33ac88-a6f7-4425-ab81-40d3c4512c80', 'artist', 'fb2c703f-5362-47dd-ada0-7c6d5e106f3b');  -- Dioni Fernández y El Equipo (en) -> Dioni Fernández
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('1971d182-412a-4686-95a9-babdec4cc738', '60c8a3fe-d52f-4f2b-8819-f76c653ee7e4', 'artist', '2bc36959-dcce-4e10-9ecf-2cd418eaa489');  -- Dioni Fernández y El Equipo (en) -> Wilfrido Vargas
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('1971d182-412a-4686-95a9-babdec4cc738', 'f5008bf2-9e35-4159-afb3-21a11b28c85e', 'artist', '3f8bafec-e5ee-415d-8405-9551cceeeb9b');  -- Dioni Fernández y El Equipo (en) -> Johnny Ventura
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('1971d182-412a-4686-95a9-babdec4cc738', '2c85fa96-f8e7-4716-8449-353b3e450302', 'artist', '3f8bafec-e5ee-415d-8405-9551cceeeb9b');  -- Dioni Fernández y El Equipo (en) -> Johnny Ventura
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('1971d182-412a-4686-95a9-babdec4cc738', 'f9075a47-34e8-4e7b-936f-8d05fa758297', 'artist', 'fb2c703f-5362-47dd-ada0-7c6d5e106f3b');  -- Dioni Fernández y El Equipo (en) -> Dioni Fernández
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('1971d182-412a-4686-95a9-babdec4cc738', 'e722534f-a710-442d-b342-2ae603eb1385', 'artist', '2bc36959-dcce-4e10-9ecf-2cd418eaa489');  -- Dioni Fernández y El Equipo (en) -> Wilfrido Vargas
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('1971d182-412a-4686-95a9-babdec4cc738', '6fe8b6d7-297d-4dd6-8aa2-9be0f8b69c40', 'artist', '3f8bafec-e5ee-415d-8405-9551cceeeb9b');  -- Dioni Fernández y El Equipo (en) -> Johnny Ventura
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('e10dd243-8076-4973-97b1-83c9e615f88b', 'c10b12c0-2d94-410a-ae97-b3f46acbaa40', 'artist', 'ea77d6c8-791d-4faa-943d-eb54cc9a0377');  -- Bonny Cepeda (en) -> Richie Cepeda
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('8d77d6da-fc7c-4d68-a3d0-5a606a1e6e36', '4760d53f-ad53-43bc-a0f5-c43d30336919', 'artist', 'ea77d6c8-791d-4faa-943d-eb54cc9a0377');  -- Bonny Cepeda (es) -> Richie Cepeda
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('eb0a07d6-d9d5-4b7b-b87d-290225bad599', '0b3e4e70-ffe7-4d29-8d75-3a8071b9c463', 'artist', 'e005898c-4fcc-45da-b857-c6775e92fa52');  -- Mario Díaz (en) -> Johnny Pacheco
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('1f95bbbc-e962-4ab8-b618-8a868eeea217', '2c50c31f-bcf0-4d9c-b507-4055ff634850', 'artist', 'e005898c-4fcc-45da-b857-c6775e92fa52');  -- Mario Díaz (es) -> Johnny Pacheco
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('a441f11a-7746-413f-a598-9793c9f43c1e', '6e8c6291-0fd5-4a38-a398-bed62238e14e', 'artist', '10034596-47cb-46ba-9e80-9ea319a2c0df');  -- Maridalia Hernández (es) -> Juan Luis Guerra
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('a441f11a-7746-413f-a598-9793c9f43c1e', '6f784387-4604-4753-b392-ff8c303fa0a6', 'artist', '4d3a653c-688e-47c1-8cec-b8cf85a4abac');  -- Maridalia Hernández (es) -> Manuel Tejada
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('a441f11a-7746-413f-a598-9793c9f43c1e', '318454b3-cafa-4ee7-8c68-c78d49176aa1', 'artist', '10034596-47cb-46ba-9e80-9ea319a2c0df');  -- Maridalia Hernández (es) -> Juan Luis Guerra
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('a441f11a-7746-413f-a598-9793c9f43c1e', 'f5668b02-c535-4890-87a1-2e4cbb917d41', 'artist', '4d3a653c-688e-47c1-8cec-b8cf85a4abac');  -- Maridalia Hernández (es) -> Manuel Tejada
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('a441f11a-7746-413f-a598-9793c9f43c1e', '5fe8e0b7-b46f-4dbf-a5ba-fa5e0d098113', 'artist', '02f23257-1cf6-4a4c-8df1-1f9aa630a2c3');  -- Maridalia Hernández (es) -> Ramón Orlando
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('a441f11a-7746-413f-a598-9793c9f43c1e', 'a73201d3-6454-45b9-9bbf-e75f5104ef46', 'artist', '9333da06-ad03-44eb-9b81-c21d0ccdd0ea');  -- Maridalia Hernández (es) -> Fefita La Grande
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('a441f11a-7746-413f-a598-9793c9f43c1e', 'b99ea11c-a8c8-4ac7-b10b-19e04ec510bc', 'artist', '10034596-47cb-46ba-9e80-9ea319a2c0df');  -- Maridalia Hernández (es) -> Juan Luis Guerra
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('04d653bc-be32-4cf5-8ddf-f231fda87bcf', '69a9fc92-57cf-4f4c-b666-e78f9672d6cf', 'artist', '059a9e99-5d11-433e-97b9-9c35e57908f1');  -- Zeo Muñoz (en) -> Sergio Vargas
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('68a51f4d-e669-4a89-b518-3f0eead1f8ad', '242940ce-6697-4dd3-ba1d-337cc2b8eef4', 'artist', '059a9e99-5d11-433e-97b9-9c35e57908f1');  -- Zeo Muñoz (es) -> Sergio Vargas
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('0d0ef9ea-2fcb-438d-b169-d3052afe7b87', '76391d24-119b-40fc-ba08-7d324acc69b6', 'artist', 'fb2c703f-5362-47dd-ada0-7c6d5e106f3b');  -- Dioni Fernández y El Equipo (es) -> Dioni Fernández
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('0d0ef9ea-2fcb-438d-b169-d3052afe7b87', '3f6e3d09-0b57-4649-a607-d48027c7e342', 'artist', '2bc36959-dcce-4e10-9ecf-2cd418eaa489');  -- Dioni Fernández y El Equipo (es) -> Wilfrido Vargas
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('0d0ef9ea-2fcb-438d-b169-d3052afe7b87', '4ff37a1d-68d0-475d-a13c-7ae62dbf920b', 'artist', '3f8bafec-e5ee-415d-8405-9551cceeeb9b');  -- Dioni Fernández y El Equipo (es) -> Johnny Ventura
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('0d0ef9ea-2fcb-438d-b169-d3052afe7b87', '6aa44f01-aff1-4e25-90e3-54e7b2e90d00', 'artist', '3f8bafec-e5ee-415d-8405-9551cceeeb9b');  -- Dioni Fernández y El Equipo (es) -> Johnny Ventura
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('0d0ef9ea-2fcb-438d-b169-d3052afe7b87', 'e496511d-3193-43b9-b80b-2bed9752bc04', 'artist', 'fb2c703f-5362-47dd-ada0-7c6d5e106f3b');  -- Dioni Fernández y El Equipo (es) -> Dioni Fernández
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('64d3ff4f-1d80-4278-8605-d38308c48be0', '06880bd8-8561-4fa4-a37f-1cdae5624ba0', 'artist', '3f8bafec-e5ee-415d-8405-9551cceeeb9b');  -- Rubby Pérez (en) -> Johnny Ventura
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('47385195-954b-4d6b-8f92-a764bfe7ea24', 'f87afa6a-ee79-4e93-966e-fce7f5f61e0d', 'artist', '052b710d-e91f-41c6-94ac-480100f95f5b');  -- July Mateo "Rasputín" (en) -> July Mateo
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('97faf784-b953-448e-a4d8-6e9e63c99428', '9856b6ed-282c-499a-b247-2134ee489fa5', 'artist', '052b710d-e91f-41c6-94ac-480100f95f5b');  -- July Mateo "Rasputín" (es) -> July Mateo
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('bd304917-726f-486b-a211-e87661aa4287', '33f9dff0-ef1b-47d6-af43-1bc36d821b65', 'artist', '3f8bafec-e5ee-415d-8405-9551cceeeb9b');  -- Milly Quezada (es) -> Johnny Ventura
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('06542874-8abe-4c57-8020-3c7913950cb4', '6e0e41e8-8bcf-4b1d-82be-560ea8b07807', 'artist', 'e005898c-4fcc-45da-b857-c6775e92fa52');  -- Johnny Ventura (en) -> Johnny Pacheco
INSERT INTO editorial_entity_references (editorial_document_id, occurrence_id, entity_type, target_artist_id)
VALUES ('9aa783db-9404-453b-9d91-47702606f037', '4c78a510-e958-4b4d-848c-ebfc2c31e8e6', 'artist', '4b4bf9da-fe4a-4fc6-be40-1b1b5413dfb3');  -- Sonia Silvestre (en) -> Víctor Víctor

-- Relation rows whose occurrence_id appears in no node of their document,
-- left behind when an edit removed the mention. Blocking findings in their own
-- right; nothing renders from them.
DELETE FROM editorial_entity_references WHERE editorial_document_id = '0fd727cf-c3fd-4583-9274-380280884931' AND occurrence_id = 'e3549075-4b3f-453f-a849-53e9c5bd2fb3';
DELETE FROM editorial_entity_references WHERE editorial_document_id = '42f37686-09ac-4ad8-b6f8-72e150808b07' AND occurrence_id = 'd4ffbb46-99ff-49d7-99aa-187e9367ecef';
DELETE FROM editorial_entity_references WHERE editorial_document_id = 'bbda8797-0236-4a5d-9d8b-6171564d68cc' AND occurrence_id = 'f0b69357-1b52-4cd7-a21e-dd5d26002ebe';
DELETE FROM editorial_entity_references WHERE editorial_document_id = '965af113-b50e-4d1a-b7e2-1cc1070dca03' AND occurrence_id = '66794731-635f-41af-8a10-2707e434962a';

COMMIT;
