BEGIN;

-- Final style list for every artist whose genres[] this pass changed.
--
-- The column held 370 entries across 130 distinct values matching no row in
-- `genres`: casing and accent drift ('Dembow' beside 'dembow', a mojibake
-- 'fusion'), English/Spanish duplicates, an occupation ('producer') filed as a
-- genre, and a long tail of styles outside a Dominican-specialised catalogue --
-- 'latin', 'world music', 'kizomba', 'Zarzuela', the pop and alternative
-- clusters. Those are dropped; the taxonomy is the statement of which genres
-- apply here.
--
-- This was not cosmetic. The artist directory builds its filter options by
-- normalising values but queries with an exact array match, so a 'Dembow' chip
-- appeared and then matched nobody stored as 'Dembow'.
--
-- Values restating the artist's own primary_genre are removed as well, per the
-- field-hygiene rule: a style must add to the primary classification, not
-- repeat it.
--
-- No published artist lost their last genre signal; that was verified before
-- the change was applied.
WITH target(slug, genres) AS (
    VALUES
      ('23thierno', ARRAY['urban-trap']::text[]),
      ('abel', ARRAY['ballads']::text[]),
      ('adalgisa-pantaleon', ARRAY['bachata','bolero']::text[]),
      ('adonis-produciendo', ARRAY['urbano','urban-reggaeton']::text[]),
      ('adriel-music', ARRAY['urbano']::text[]),
      ('adriel-sfx', ARRAY['instrumental']::text[]),
      ('aisha-syed-castro', '{}'::text[]),
      ('akinohayley', ARRAY['urban-rap-hip-hop']::text[]),
      ('alberto-beltran', ARRAY['merengue']::text[]),
      ('alejandro-torrens', ARRAY['bolero']::text[]),
      ('alex-diaz', ARRAY['merengue']::text[]),
      ('alex-ferreira', '{}'::text[]),
      ('alex-linares', '{}'::text[]),
      ('alex-matos', ARRAY['ballads']::text[]),
      ('alexandra-queen', '{}'::text[]),
      ('alih-jey', '{}'::text[]),
      ('amarfis', ARRAY['merengue-mambo']::text[]),
      ('amarfis-y-la-banda-de-atakke', ARRAY['merengue']::text[]),
      ('amenazzy', ARRAY['urbano']::text[]),
      ('anais', '{}'::text[]),
      ('andre-parra-marte', '{}'::text[]),
      ('andres-rodriguez', ARRAY['ballads']::text[]),
      ('angel-dior', ARRAY['urbano']::text[]),
      ('angela-carrasco', ARRAY['merengue','ballads-romantic']::text[]),
      ('anon-muller', '{}'::text[]),
      ('antidoto-casero', ARRAY['reggae']::text[]),
      ('antihippie', ARRAY['urbano']::text[]),
      ('antony-santos', ARRAY['merengue-perico-ripiao']::text[]),
      ('apofis-imn', ARRAY['urban-rap-hip-hop','urbano']::text[]),
      ('aposento-alto', ARRAY['urbano']::text[]),
      ('archaios', '{}'::text[]),
      ('arrozito', '{}'::text[]),
      ('barak', '{}'::text[]),
      ('bartolito-y-los-bravos-del-son', '{}'::text[]),
      ('beethoven-villaman', ARRAY['urbano']::text[]),
      ('black-45-king', ARRAY['urbano']::text[]),
      ('blackee-impala', ARRAY['urbano']::text[]),
      ('blackfox', '{}'::text[]),
      ('bladimir-vasquez', ARRAY['urban-reggaeton']::text[]),
      ('blas-duran', '{}'::text[]),
      ('bocatabu', '{}'::text[]),
      ('brandom-regino', ARRAY['worship']::text[]),
      ('bryan-dotel', ARRAY['ballads']::text[]),
      ('bs-el-ideologo', ARRAY['urbano','urban-trap']::text[]),
      ('bulin-47', ARRAY['urbano']::text[]),
      ('bullumba-landestoy', ARRAY['instrumental-classical']::text[]),
      ('carlos-alfredo-fatule', ARRAY['merengue']::text[]),
      ('carlos-manuel-vargas', '{}'::text[]),
      ('chimbala', ARRAY['urban-reggaeton','urban-dembow']::text[]),
      ('chris-alflow', ARRAY['urban-dembow']::text[]),
      ('cuco-valoy', ARRAY['folklore-son-dominicano']::text[]),
      ('damiron', ARRAY['folklore-dominicano']::text[]),
      ('daniel-moncion', '{}'::text[]),
      ('daniel-santacruz', ARRAY['merengue']::text[]),
      ('dario-estrella', ARRAY['merengue','fusion']::text[]),
      ('dary-hezz', ARRAY['urban-dembow','urban-reggaeton']::text[]),
      ('david-appleton', ARRAY['fusion']::text[]),
      ('derick-daniel-perez-cordero', ARRAY['fusion']::text[]),
      ('devin', ARRAY['bachata']::text[]),
      ('deyvi-sime', ARRAY['jazz']::text[]),
      ('dj-adoni', ARRAY['urban-reggaeton','urbano','merengue','bachata','salsa']::text[]),
      ('dj-arelis-hot', ARRAY['merengue','urbano','urban-rap-hip-hop']::text[]),
      ('dj-gabriel-b', ARRAY['urbano','urban-dembow']::text[]),
      ('dj-joe-catador', ARRAY['urbano','urban-reggaeton']::text[]),
      ('dj-mari-d', ARRAY['urban-rap-hip-hop']::text[]),
      ('dj-plano', ARRAY['urbano']::text[]),
      ('dj-scuff', ARRAY['urban-rap-hip-hop','urban-dembow','urban-reggaeton','urban-trap']::text[]),
      ('dj-urba', ARRAY['urbano']::text[]),
      ('domingo-philharmonic-orchestra', ARRAY['instrumental-orchestral','instrumental']::text[]),
      ('dominic', '{}'::text[]),
      ('don-miguelo', ARRAY['urban-dembow','urban-reggaeton']::text[]),
      ('donaty', '{}'::text[]),
      ('donny-whey', ARRAY['urban-dembow','urban-reggaeton']::text[]),
      ('draconum-oth', '{}'::text[]),
      ('duluc', ARRAY['fusion','rock']::text[]),
      ('egleyda-belliard', ARRAY['worship']::text[]),
      ('eilyn-paulina', '{}'::text[]),
      ('eklectico', ARRAY['urban-dembow']::text[]),
      ('el-alfa', ARRAY['urbano','urban-reggaeton']::text[]),
      ('el-cata', '{}'::text[]),
      ('el-cherry-scom', ARRAY['urban-reggaeton']::text[]),
      ('el-fecho-rd', '{}'::text[]),
      ('el-prodigio', ARRAY['jazz','merengue']::text[]),
      ('el-trio', '{}'::text[]),
      ('emetede', ARRAY['urban-dembow']::text[]),
      ('emil-cerda', '{}'::text[]),
      ('enerolisa-nunez', '{}'::text[]),
      ('enrique-de-marchena', '{}'::text[]),
      ('esme', '{}'::text[]),
      ('expresion-joven', ARRAY['folklore']::text[]),
      ('fair-trade', '{}'::text[]),
      ('felipe-a-linares', '{}'::text[]),
      ('felix-del-rosario', ARRAY['jazz']::text[]),
      ('fernando-echavarria', ARRAY['merengue']::text[]),
      ('fernando-villalona', ARRAY['bolero','ballads']::text[]),
      ('flow-28', ARRAY['urbano']::text[]),
      ('fortuna-la-super-f', ARRAY['urban-reggaeton']::text[]),
      ('francikario', ARRAY['urbano']::text[]),
      ('francisco-casanova', '{}'::text[]),
      ('frecox-unic', ARRAY['urban-trap']::text[]),
      ('gabriel-del-orbe', '{}'::text[]),
      ('gabriel-pagan', '{}'::text[]),
      ('gangrena-cerebral', '{}'::text[]),
      ('gda-el-unico', ARRAY['urban-dembow']::text[]),
      ('genoveva-la-patrona', ARRAY['merengue','urban-reggaeton']::text[]),
      ('ghetto', ARRAY['urbano','urban-trap']::text[]),
      ('gior-chambonea', '{}'::text[]),
      ('grunjeo', '{}'::text[]),
      ('grupo-extra', '{}'::text[]),
      ('guillermo', '{}'::text[]),
      ('hancel-osorius', ARRAY['instrumental-classical']::text[]),
      ('haraca-kiko', ARRAY['urban-dembow']::text[]),
      ('hector-santana', ARRAY['jazz']::text[]),
      ('henry-santos', ARRAY['urbano']::text[]),
      ('hollywood', '{}'::text[]),
      ('ilegales', ARRAY['urbano']::text[]),
      ('indhira-rubiera', '{}'::text[]),
      ('indigo', '{}'::text[]),
      ('inka', ARRAY['urban-rap-hip-hop']::text[]),
      ('iris-franklyn', '{}'::text[]),
      ('irka-mateo', ARRAY['fusion']::text[]),
      ('ito-ogamy', ARRAY['urban-rap-hip-hop']::text[]),
      ('j-a', ARRAY['urbano']::text[]),
      ('j-noa', ARRAY['urbano']::text[]),
      ('jabes', ARRAY['worship-gospel']::text[]),
      ('jacinto-gimbernard', '{}'::text[]),
      ('jairo-puello', ARRAY['worship-gospel']::text[]),
      ('jandy-feliz', '{}'::text[]),
      ('janina-rosado', ARRAY['bachata','jazz','fusion']::text[]),
      ('jankobow', '{}'::text[]),
      ('jay-miky-flow', ARRAY['urbano','urban-reggaeton']::text[]),
      ('jc', ARRAY['urban-trap']::text[]),
      ('jeffrey-henriquez-rijo', ARRAY['instrumental-classical','bachata','urban-reggaeton']::text[]),
      ('jesus-juan-antonio', '{}'::text[]),
      ('jeyless', '{}'::text[]),
      ('jezzy', ARRAY['urbano']::text[]),
      ('jhoni-the-voice', ARRAY['urbano']::text[]),
      ('joa-el-super-mc', ARRAY['urbano']::text[]),
      ('joan-soriano', '{}'::text[]),
      ('jodio-loco-sucio', '{}'::text[]),
      ('johnny-pacheco', '{}'::text[]),
      ('joly-sc', ARRAY['urban-rap-hip-hop','urban-dembow']::text[]),
      ('jorge-luis-rosario-rodriguez', ARRAY['instrumental-classical']::text[]),
      ('jorge-morel', ARRAY['instrumental-classical']::text[]),
      ('jorge-taveras', ARRAY['ballads']::text[]),
      ('jose-antonio-rodriguez', '{}'::text[]),
      ('jose-batista-fuchi', ARRAY['folklore-dominicano']::text[]),
      ('jose-bello', '{}'::text[]),
      ('jose-luis-hernandez-moreno', '{}'::text[]),
      ('jose-rufino-reyes-y-siancas', '{}'::text[]),
      ('josean-jacobo', ARRAY['fusion']::text[]),
      ('jp-rmt', ARRAY['urban-rap-hip-hop']::text[]),
      ('juan-bautista-alfonseca', ARRAY['instrumental-classical','folklore-dominicano']::text[]),
      ('juan-colon', ARRAY['jazz']::text[]),
      ('juan-francisco-garcia', ARRAY['folklore-dominicano']::text[]),
      ('juan-francisco-ordonez', ARRAY['bachata','jazz']::text[]),
      ('juliana-o-neal', ARRAY['merengue-mambo']::text[]),
      ('kalimete', ARRAY['urbano']::text[]),
      ('karlos-rose', ARRAY['urbano']::text[]),
      ('keren-montero', '{}'::text[]),
      ('kiko-el-crazy', ARRAY['urbano']::text[]),
      ('killer-rap', ARRAY['urbano']::text[]),
      ('king-caballero', '{}'::text[]),
      ('king-streetz', ARRAY['urbano']::text[]),
      ('la-armada', ARRAY['urbano']::text[]),
      ('la-baby', ARRAY['urban-dembow']::text[]),
      ('la-india-canela', ARRAY['merengue']::text[]),
      ('la-insuperable', ARRAY['urban-dembow']::text[]),
      ('la-materialista', ARRAY['urban-dembow']::text[]),
      ('la-noe-aposento-alto', ARRAY['urbano']::text[]),
      ('la-pajarita-la-paul', ARRAY['urban-dembow']::text[]),
      ('lapiitoh-dangers', ARRAY['urbano']::text[]),
      ('lapiz-conciente', '{}'::text[]),
      ('las-gemelas-fantasticas-rd', '{}'::text[]),
      ('lenny-santana', '{}'::text[]),
      ('leny', '{}'::text[]),
      ('leo-rd', ARRAY['urbano']::text[]),
      ('leonor-porcella-de-brea', ARRAY['bolero']::text[]),
      ('lismar', ARRAY['urban-dembow','urban-drill']::text[]),
      ('lizzy-parra', ARRAY['urbano','worship']::text[]),
      ('lolo-en-el-microfono', '{}'::text[]),
      ('los-congos-del-espiritu-santo', '{}'::text[]),
      ('los-homeboys', ARRAY['merengue-house','urbano']::text[]),
      ('los-sufridos', '{}'::text[]),
      ('lucien-le-grub', '{}'::text[]),
      ('luigui-bleand', ARRAY['urban-rap-hip-hop']::text[]),
      ('luis-alberti', ARRAY['folklore','bolero']::text[]),
      ('luis-aquino', ARRAY['salsa']::text[]),
      ('luis-armando-rivera-gonzalez', ARRAY['merengue','bolero']::text[]),
      ('luis-caracter', '{}'::text[]),
      ('luis-kalaff', ARRAY['folklore','bolero','folklore-salve']::text[]),
      ('luis-pimentel', ARRAY['folklore']::text[]),
      ('luis-pimentel-y-su-conjunto-de-estrellas', ARRAY['folklore']::text[]),
      ('luna-drums', '{}'::text[]),
      ('luny', ARRAY['urbano']::text[]),
      ('luny-tunes', '{}'::text[]),
      ('luys-bien', ARRAY['bachata','salsa','merengue-pambiche','bolero']::text[]),
      ('maffio', ARRAY['bachata','merengue','urban-reggaeton']::text[]),
      ('mamajuana', '{}'::text[]),
      ('manny-cruz', ARRAY['bachata']::text[]),
      ('manuel-de-jesus-jimenez-ortega', ARRAY['bachata','ballads']::text[]),
      ('manuel-miller', '{}'::text[]),
      ('manuel-simo', ARRAY['instrumental-classical']::text[]),
      ('manuel-tejada', '{}'::text[]),
      ('marcos-yaroide', '{}'::text[]),
      ('maria-diaz', ARRAY['merengue']::text[]),
      ('maridalia-hernandez', ARRAY['bachata']::text[]),
      ('mario-de-jesus-baez', ARRAY['merengue','salsa']::text[]),
      ('mario-rivera', ARRAY['salsa']::text[]),
      ('martha-candela', ARRAY['merengue-urbano']::text[]),
      ('martha-heredia', ARRAY['urban-reggaeton']::text[]),
      ('mc-wayne', ARRAY['urban-rap-hip-hop']::text[]),
      ('melymel', ARRAY['urbano']::text[]),
      ('messiah', ARRAY['urbano','urban-rap-hip-hop']::text[]),
      ('michel-camilo', ARRAY['instrumental-classical']::text[]),
      ('mickey-dastinz', ARRAY['urban-rap-hip-hop']::text[]),
      ('mickey-taveras', ARRAY['bachata','merengue']::text[]),
      ('milka-la-mas-dura', ARRAY['urbano']::text[]),
      ('monkey-black', ARRAY['urbano']::text[]),
      ('morbid', '{}'::text[]),
      ('moria', ARRAY['urbano']::text[]),
      ('mozart-la-para', ARRAY['urban-reggaeton','urbano']::text[]),
      ('mr-yeison', ARRAY['urban-dembow']::text[]),
      ('mula', ARRAY['urbano']::text[]),
      ('musicologo-the-libro', ARRAY['urban-reggaeton','urban-rap-hip-hop']::text[]),
      ('musiquito', '{}'::text[]),
      ('nancy-amancio', ARRAY['ballads']::text[]),
      ('natan-el-profeta', ARRAY['merengue-urbano','urban-reggaeton']::text[]),
      ('natti-natasha', ARRAY['bachata','urbano']::text[]),
      ('necro', ARRAY['urbano']::text[]),
      ('negrito-chapuseaux', ARRAY['bolero']::text[]),
      ('nelson-de-la-olla', '{}'::text[]),
      ('nico-clinico', ARRAY['urban-reggaeton']::text[]),
      ('nini-caffaro', ARRAY['ballads-bolero']::text[]),
      ('nino-freestyle', ARRAY['urban-rap-hip-hop']::text[]),
      ('ninon-lapeiretta-de-brouwer', '{}'::text[]),
      ('nmnl', ARRAY['urbano']::text[]),
      ('omega', ARRAY['merengue']::text[]),
      ('orquesta-in-art', '{}'::text[]),
      ('orquesta-la-muralla', '{}'::text[]),
      ('oscar-dominic', '{}'::text[]),
      ('oscar-micheli', '{}'::text[]),
      ('ovni-exp', '{}'::text[]),
      ('palmer-hernandez', ARRAY['bachata']::text[]),
      ('papaa-tyga', ARRAY['urbano']::text[]),
      ('papi-sanchez', '{}'::text[]),
      ('pavel-nunez', '{}'::text[]),
      ('petiton-guzman', '{}'::text[]),
      ('pirou-perez', '{}'::text[]),
      ('pochy-y-su-cocoband', '{}'::text[]),
      ('rafael-solano', ARRAY['bolero','merengue','folklore']::text[]),
      ('ramon-torres', '{}'::text[]),
      ('raulin-rodriguez', '{}'::text[]),
      ('reychesta-secret-weapon', ARRAY['urban-rap-hip-hop']::text[]),
      ('richie-cepeda', '{}'::text[]),
      ('rubinsky-rbk', ARRAY['urban-reggaeton']::text[]),
      ('sammy-the-greatest', ARRAY['urbano','urban-reggaeton']::text[]),
      ('sandy-gabriel', ARRAY['fusion']::text[]),
      ('secreto-el-famoso-biberon', ARRAY['urban-reggaeton','merengue-urbano']::text[]),
      ('sharlene', '{}'::text[]),
      ('teodoro-reyes', '{}'::text[]),
      ('tokischa', ARRAY['urban-dembow']::text[]),
      ('twovm-para-cristo', ARRAY['urbano']::text[]),
      ('vicente-garcia', ARRAY['merengue','reggae']::text[]),
      ('xiomara-fortuna', ARRAY['jazz']::text[]),
      ('yovanny-polanco', ARRAY['merengue-perico-ripiao']::text[])
)
UPDATE artists a
SET genres = t.genres,
    updated_at = now()
FROM target t
WHERE a.slug = t.slug
  AND a.genres IS DISTINCT FROM t.genres;

COMMIT;
