BEGIN;

-- Final classification for every artist whose primary_genre this pass changed.
--
-- Before: 131 artists carried a primary_genre matching no row in `genres`.
-- Values like 'urban', 'dembow', 'rap', 'classical' and 'other' resolved to
-- nothing, so those artists were absent from the genre pages they belonged to.
-- Each is mapped to the taxonomy slug denoting the same thing, preserving the
-- level: 'dembow' becomes the level-1 'urban-dembow', not the level-0 'urbano',
-- so no editorial specificity is flattened.
--
-- The 'pop' and 'other' buckets were editorial decisions rather than mechanical
-- mappings. Mangulina catalogues Dominican music specifically and pop is not a
-- genre in this taxonomy; those artists were classified individually, and the
-- ones awaiting review carry NULL rather than a placeholder that would have to
-- be undone later.
--
-- Stated as explicit final values rather than replayed transformations, so the
-- outcome cannot drift with execution order, and re-running is a no-op.
WITH target(slug, primary_genre) AS (
    VALUES
      ('abel', NULL),
      ('adonis-produciendo', 'urban-dembow'),
      ('adriel-music', 'urban-dembow'),
      ('adriel-sfx', 'urbano'),
      ('akinohayley', 'urbano'),
      ('alex-ferreira', 'rock'),
      ('alex-linares', 'urbano'),
      ('amenazzy', 'urban-reggaeton'),
      ('anais', 'ballads'),
      ('andres-rodriguez', NULL),
      ('angel-dior', 'urban-dembow'),
      ('anthony', 'urbano'),
      ('aposento-alto', 'urban-rap-hip-hop'),
      ('arrozito', 'urbano'),
      ('barak', 'worship'),
      ('beethoven-villaman', 'urban-rap-hip-hop'),
      ('black-45-king', 'urban-rap-hip-hop'),
      ('blackee-impala', 'urban-trap'),
      ('bladimir-vasquez', 'urbano'),
      ('bocatabu', 'rock'),
      ('brandom-regino', NULL),
      ('bs-el-ideologo', 'urban-dembow'),
      ('bulin-47', 'urban-dembow'),
      ('calor-urbano', 'urbano'),
      ('carlos-manuel-vargas', 'instrumental-classical'),
      ('ceky-viciny', 'urban-dembow'),
      ('charytin', 'ballads'),
      ('chiky-bombom-la-pantera', 'urbano'),
      ('crisisromani', 'urbano'),
      ('dary-hezz', 'urbano'),
      ('david-appleton', 'instrumental-classical'),
      ('devin', 'urbano'),
      ('dj-adoni', 'urban-dembow'),
      ('dj-arelis-hot', 'urban-reggaeton'),
      ('dj-joe-catador', 'urban-dembow'),
      ('dj-plano', 'urban-dembow'),
      ('dj-urba', 'urban-reggaeton'),
      ('domingo-philharmonic-orchestra', 'instrumental-classical'),
      ('don-miguelo', 'urbano'),
      ('donny-whey', 'urbano'),
      ('eilyn-paulina', 'worship'),
      ('el-alfa', 'urban-dembow'),
      ('emetede', 'urbano'),
      ('enmanuel-richarson', 'instrumental-classical'),
      ('enrique-de-marchena', 'instrumental-classical'),
      ('felipe-a-linares', 'worship'),
      ('flow-28', 'urban-dembow'),
      ('francikario', 'urban-rap-hip-hop'),
      ('gabriel-del-orbe', 'instrumental-classical'),
      ('ghetto', 'urban-dembow'),
      ('guillermo', 'worship'),
      ('indhira-rubiera', 'instrumental-classical'),
      ('inka', 'urbano'),
      ('iris-franklyn', 'worship'),
      ('j-a', 'urban-dembow'),
      ('j-noa', 'urban-rap-hip-hop'),
      ('jabes', 'worship'),
      ('jacinto-gimbernard', 'instrumental-classical'),
      ('jairo-puello', 'worship'),
      ('jay-miky-flow', 'urban-dembow'),
      ('jeffrey-henriquez-rijo', 'urbano'),
      ('jesus-juan-antonio', 'instrumental-classical'),
      ('jeyless', 'urbano'),
      ('jezzy', 'urban-rap-hip-hop'),
      ('joa-el-super-mc', 'urban-rap-hip-hop'),
      ('joly-sc', 'urbano'),
      ('jose-luis-hernandez-moreno', 'instrumental-classical'),
      ('jp-rmt', 'urbano'),
      ('juan-francisco-garcia', 'instrumental-classical'),
      ('keren-montero', 'worship'),
      ('kikito-black', 'urbano'),
      ('kiko-el-crazy', 'urban-dembow'),
      ('killer-rap', 'urban-rap-hip-hop'),
      ('king-caballero', 'urbano'),
      ('king-streetz', 'urban-rap-hip-hop'),
      ('korven-brox', 'urbano'),
      ('la-insuperable', 'urbano'),
      ('la-materialista', 'urbano'),
      ('la-noe-aposento-alto', 'urban-rap-hip-hop'),
      ('lapiitoh-dangers', 'urban-dembow'),
      ('las-gemelas-fantasticas-rd', 'worship'),
      ('lenny-santana', 'bachata'),
      ('leny', NULL),
      ('leo-rd', 'urban-dembow'),
      ('lizzy-parra', 'urban-rap-hip-hop'),
      ('los-homeboys', 'urban-rap-hip-hop'),
      ('luis-armando-rivera-gonzalez', 'instrumental-classical'),
      ('luna-drums', 'urbano'),
      ('luny', 'urban-reggaeton'),
      ('marcos-yaroide', 'worship'),
      ('mariangel', 'urban-rap-hip-hop'),
      ('martha-heredia', 'merengue-calle'),
      ('mc-wayne', 'urbano'),
      ('melymel', 'urban-rap-hip-hop'),
      ('messiah', 'urban-trap'),
      ('milka-la-mas-dura', 'urban-dembow'),
      ('musicologo-the-libro', 'urbano'),
      ('nancy-amancio', 'worship'),
      ('natti-natasha', 'urban-reggaeton'),
      ('necro', 'urban-rap-hip-hop'),
      ('ninon-lapeiretta-de-brouwer', 'instrumental-classical'),
      ('nmnl', 'urban-rap-hip-hop'),
      ('o-g-black', 'urban-rap-hip-hop'),
      ('oasis-ministry', 'worship'),
      ('orquesta-sinfonica-nacional', 'instrumental-classical'),
      ('paramba', 'urban-dembow'),
      ('poeta-callejero', 'urban-rap-hip-hop'),
      ('profeta-lirical', 'urban-rap-hip-hop'),
      ('proytecto-uno', 'urban-rap-hip-hop'),
      ('puyalo-pantera', 'urban-dembow'),
      ('quimico-ultra-mega', 'urban-dembow'),
      ('r1-la-esencia', 'urban-rap-hip-hop'),
      ('redimi2', 'urban-rap-hip-hop'),
      ('rochy-rd', 'urban-dembow'),
      ('rosangela-abreu', NULL),
      ('rubinsky-rbk', 'urban-rap-hip-hop'),
      ('sammy-the-greatest', 'urban-dembow'),
      ('secreto-el-famoso-biberon', 'urban-dembow'),
      ('shadow-blow', 'urban-rap-hip-hop'),
      ('sharlene', 'urban-reggaeton'),
      ('shelow-shaq', 'urbano'),
      ('tercer-cielo', 'worship'),
      ('tivi-gunz', 'urbano'),
      ('tokischa', 'urban-reggaeton'),
      ('toqita', 'urbano'),
      ('toxic-crow', 'urban-rap-hip-hop'),
      ('tunes', 'urban-reggaeton'),
      ('twovm-para-cristo', 'urban-reggaeton'),
      ('vakero', 'urban-dembow'),
      ('young-grin', 'urbano')
)
UPDATE artists a
SET primary_genre = t.primary_genre,
    updated_at = now()
FROM target t
WHERE a.slug = t.slug
  AND a.primary_genre IS DISTINCT FROM t.primary_genre;

COMMIT;
