BEGIN;
CREATE OR REPLACE FUNCTION public.attach_editorial_evidence(actor uuid,key uuid,assertion_uuid uuid,source_uuid uuid,relationship_value text,notes_value text DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$ DECLARE cached jsonb; result_value jsonb; BEGIN
 PERFORM public.require_editorial_capability(actor,'assertion.create'); PERFORM pg_advisory_xact_lock(hashtextextended(actor::text||key::text,0)); cached:=public.editorial_idempotent_result(actor,'evidence.attach',key); IF cached IS NOT NULL THEN RETURN cached; END IF;
 IF relationship_value NOT IN('supports','disputes','contextualizes') THEN RAISE EXCEPTION 'invalid evidence relationship'; END IF;
 INSERT INTO public.editorial_assertion_evidence(assertion_id,source_id,relationship,notes,created_by) VALUES(assertion_uuid,source_uuid,relationship_value,nullif(btrim(notes_value),''),actor) ON CONFLICT DO NOTHING;
 INSERT INTO public.editorial_audit_events(event_type,actor_type,actor_user_id,table_name,row_id,after_state,reason) VALUES('evidence.attached','human_editor',actor,'editorial_assertions',assertion_uuid,jsonb_build_object('source_id',source_uuid,'relationship',relationship_value),'Evidence attached');
 result_value:=jsonb_build_object('assertion_id',assertion_uuid,'source_id',source_uuid,'relationship',relationship_value); INSERT INTO public.editorial_idempotency_keys VALUES(actor,'evidence.attach',key,result_value,now()); RETURN result_value; END $$;

CREATE OR REPLACE FUNCTION public.request_recording_work_unlink(actor uuid,key uuid,recording_uuid uuid,reason_value text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$ DECLARE cached jsonb; old_work uuid; assertion_uuid uuid; decision_uuid uuid; result_value jsonb; BEGIN
 PERFORM public.require_editorial_capability(actor,'work.link_recording'); IF length(btrim(coalesce(reason_value,'')))<10 THEN RAISE EXCEPTION 'meaningful unlink reason required'; END IF; PERFORM pg_advisory_xact_lock(hashtextextended(actor::text||key::text,0)); cached:=public.editorial_idempotent_result(actor,'recording_work.unlink',key); IF cached IS NOT NULL THEN RETURN cached; END IF;
 SELECT work_id INTO old_work FROM public.recordings WHERE id=recording_uuid FOR UPDATE; IF old_work IS NULL THEN result_value:=jsonb_build_object('status','already_unresolved','recording_id',recording_uuid); ELSE
 INSERT INTO public.editorial_assertions(assertion_type,predicate,asserted_value,verification_status,canonical_status,internal_notes,created_by) VALUES('recording_work_relationship','recording.work_id',jsonb_build_object('recording_id',recording_uuid,'work_id',null),'under_review','unresolved',reason_value,actor) RETURNING id INTO assertion_uuid;
 INSERT INTO public.editorial_assertion_recordings VALUES(assertion_uuid,recording_uuid);
 INSERT INTO public.editorial_decisions(decision_type,status,reason,requested_by,requires_independent_approval,previous_canonical_state,resulting_canonical_state) VALUES('unlink_recording_work','requested',btrim(reason_value),actor,true,jsonb_build_object('recording_id',recording_uuid,'work_id',old_work),jsonb_build_object('recording_id',recording_uuid,'work_id',null)) RETURNING id INTO decision_uuid;
 INSERT INTO public.editorial_decision_assertions VALUES(decision_uuid,assertion_uuid,'considered'); result_value:=jsonb_build_object('status','approval_required','decision_id',decision_uuid,'assertion_id',assertion_uuid); END IF;
 INSERT INTO public.editorial_idempotency_keys VALUES(actor,'recording_work.unlink',key,result_value,now()); RETURN result_value; END $$;

CREATE OR REPLACE FUNCTION public.resolve_recording_work_decision(actor uuid,key uuid,decision_uuid uuid,resolution text,approver_note text DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$ DECLARE cached jsonb; d public.editorial_decisions; recording_uuid uuid; target_work uuid; assertion_uuid uuid; result_value jsonb; BEGIN
 PERFORM public.require_editorial_capability(actor,'decision.approve'); IF resolution NOT IN('approve','reject') THEN RAISE EXCEPTION 'resolution must be approve or reject'; END IF; PERFORM pg_advisory_xact_lock(hashtextextended(actor::text||key::text,0)); cached:=public.editorial_idempotent_result(actor,'recording_work.resolve',key); IF cached IS NOT NULL THEN RETURN cached; END IF;
 SELECT * INTO d FROM public.editorial_decisions WHERE id=decision_uuid FOR UPDATE; IF NOT FOUND OR d.status<>'requested' OR d.decision_type NOT IN('change_recording_work','unlink_recording_work') THEN RAISE EXCEPTION 'eligible pending decision not found'; END IF; IF d.requested_by=actor THEN RAISE EXCEPTION 'independent self-approval is not allowed'; END IF;
 recording_uuid:=(d.resulting_canonical_state->>'recording_id')::uuid; target_work:=nullif(d.resulting_canonical_state->>'work_id','')::uuid; SELECT assertion_id INTO assertion_uuid FROM public.editorial_decision_assertions WHERE decision_id=decision_uuid LIMIT 1;
 IF resolution='reject' THEN UPDATE public.editorial_decisions SET status='rejected',approved_by=actor,decided_by=actor,decided_at=now(),internal_notes=concat_ws(E'\n',internal_notes,nullif(btrim(approver_note),'')) WHERE id=decision_uuid; UPDATE public.editorial_assertions SET verification_status='rejected',canonical_status='unresolved',reviewed_by=actor,reviewed_at=now() WHERE id=assertion_uuid; result_value:=jsonb_build_object('status','rejected','decision_id',decision_uuid,'recording_id',recording_uuid);
 ELSE PERFORM set_config('app.governed_work_link','on',true); PERFORM set_config('app.editorial_reason',d.reason,true); UPDATE public.recordings SET work_id=target_work WHERE id=recording_uuid; UPDATE public.editorial_assertions SET verification_status='superseded',canonical_status='superseded' WHERE id IN(SELECT assertion_id FROM public.editorial_assertion_recording_work_targets WHERE recording_id=recording_uuid) AND canonical_status='accepted'; UPDATE public.editorial_assertions SET verification_status='verified',canonical_status='accepted',reviewed_by=actor,reviewed_at=now() WHERE id=assertion_uuid; PERFORM set_config('app.governed_work_link','off',true); UPDATE public.editorial_decisions SET status='executed',approved_by=actor,decided_by=actor,decided_at=now(),internal_notes=concat_ws(E'\n',internal_notes,nullif(btrim(approver_note),'')) WHERE id=decision_uuid; result_value:=jsonb_build_object('status','executed','decision_id',decision_uuid,'recording_id',recording_uuid,'work_id',target_work); END IF;
 INSERT INTO public.editorial_audit_events(event_type,actor_type,actor_user_id,decision_id,table_name,row_id,after_state,reason) VALUES('recording_work.'||CASE WHEN resolution='approve' THEN 'approved' ELSE 'rejected' END,'human_editor',actor,decision_uuid,'recordings',recording_uuid,CASE WHEN resolution='approve' THEN d.resulting_canonical_state ELSE d.previous_canonical_state END,d.reason);
 INSERT INTO public.editorial_idempotency_keys VALUES(actor,'recording_work.resolve',key,result_value,now()); RETURN result_value; END $$;

REVOKE ALL ON FUNCTION public.attach_editorial_evidence(uuid,uuid,uuid,uuid,text,text),public.request_recording_work_unlink(uuid,uuid,uuid,text),public.resolve_recording_work_decision(uuid,uuid,uuid,text,text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.attach_editorial_evidence(uuid,uuid,uuid,uuid,text,text),public.request_recording_work_unlink(uuid,uuid,uuid,text),public.resolve_recording_work_decision(uuid,uuid,uuid,text,text) TO service_role;
NOTIFY pgrst,'reload schema'; COMMIT;
